-- Creación del usuario 
CREATE USER SGPC IDENTIFIED BY Fidelitas20262Q$;

-- Permite la conexión con la base de datos
GRANT CREATE SESSION TO SGPC;

-- Esto permite ser un esquema
GRANT RESOURCE TO SGPC;

-- Ampliación de Table Space
ALTER USER SGPC
QUOTA UNLIMITED ON DATA;

-- En esta sección se crea la función para validar la contraseña 
CREATE OR REPLACE FUNCTION BIBLIOTECOLOGIA_VERIFICACION_SEGURIDAD(
USERNAME VARCHAR2,
PASSWORD VARCHAR2,
OLD_PASSWORD VARCHAR2
) RETURN BOOLEAN IS
BEGIN 
IF LENGTH (Password)<12 THEN
    RAISE_APPLICATION_ERROR(-20001, 'LA CONTRASEÑA DEBE CONTENER AL MENOS 13 CARACTERES');
END IF; 

IF NOT REGEXP_LIKE(Password, '[A-Z]') THEN
    RAISE_APPLICATION_ERROR(-20002, 'LA CONTRASEÑA DEBE CONTENER AL MENOS 1 CARACTER EN MAYÚSCULA');
END IF; 

IF NOT REGEXP_LIKE(Password, '[a-z]') THEN
    RAISE_APPLICATION_ERROR(-20003, 'LA CONTRASEÑA DEBE CONTENER AL MENOS 1 CARACTER EN MINÚSCULA');
END IF; 

IF NOT REGEXP_LIKE(Password, '[0-9]') THEN
    RAISE_APPLICATION_ERROR(-20004, 'LA CONTRASEÑA DEBE CONTENER AL MENOS 1 NÚMERO');
END IF;

IF NOT REGEXP_LIKE(Password, '[^A-Za-z0-9]') THEN
    RAISE_APPLICATION_ERROR(-20005, 'LA CONTRASEÑA DEBE CONTENER AL MENOS 1 CARACTER ESPECIAL');
END IF;

IF REGEXP_LIKE(Password, '(.)\1') THEN
    RAISE_APPLICATION_ERROR(-20006, 'LA CONTRASEÑA NO DEBE REPETIR CARACTERES');
END IF;

IF REGEXP_LIKE(Password, '\s') THEN
    RAISE_APPLICATION_ERROR(-20007, 'LA CONTRASEÑA NO DEBE CONTENER ESPACIOS EN BLANCO');
END IF;

IF REGEXP_LIKE(LOWER(Password),'123456789101112|oracle|abdcefghijklmn') THEN
    RAISE_APPLICATION_ERROR(-20008, 'CONTRASEÑA DÉBIL');
END IF;

IF OLD_PASSWORD IS NOT NULL AND PASSWORD = OLD_PASSWORD THEN
    RAISE_APPLICATION_ERROR(-20008, 'LA NUEVA CONTRASEÑA NO PUEDE SER IGUAL A LA ANTERIOR');
END IF;

IF INSTR (LOWER(PASSWORD),LOWER(USERNAME))>0 THEN
    RAISE_APPLICATION_ERROR(-20010, 'LA NUEVA CONTRASEÑA NO PUEDE SER IGUAL AL USUSARIO');
END IF;

RETURN TRUE;

END;
/

-- En esta sección se crea el perfil BIBLIOTECOLOGIA_PERFIL_SEGURIDAD   
CREATE PROFILE BIBLIOTECOLOGIA_PERFIL_SEGURIDAD LIMIT
    SESSIONS_PER_USER 1
    FAILED_LOGIN_ATTEMPTS 3
    PASSWORD_LIFE_TIME 90
    PASSWORD_REUSE_MAX 5
    PASSWORD_VERIFY_FUNCTION ADMIN.BIBLIOTECOLOGIA_VERIFICACION_SEGURIDAD;

ALTER USER SGPC PROFILE BIBLIOTECOLOGIA_PERFIL_SEGURIDAD;

-- ROLES
CREATE ROLE FIDE_DOCENTE_ROL;
CREATE ROLE FIDE_COMISION_ROL NOT IDENTIFIED;
CREATE ROLE FIDE_COORDINADOR_ROL NOT IDENTIFIED;
CREATE ROLE FIDE_ADMINISTRADOR_ROL NOT IDENTIFIED;

-- CREACION DE USUARIOS DEL SISTEMA
CREATE USER USUARIO_DOCENTE IDENTIFIED BY DocenteBib$2026;
GRANT CREATE SESSION TO USUARIO_DOCENTE;
GRANT RESOURCE TO USUARIO_DOCENTE;

CREATE USER USUARIO_COMISION IDENTIFIED BY ComisionBib$2026;
GRANT CREATE SESSION TO USUARIO_COMISION;
GRANT RESOURCE TO USUARIO_COMISION;

CREATE USER USUARIO_COORDINADOR IDENTIFIED BY CoordinadorBib$2026;
GRANT CREATE SESSION TO USUARIO_COORDINADOR;
GRANT RESOURCE TO USUARIO_COORDINADOR;

CREATE USER USUARIO_ADMINISTRADOR IDENTIFIED BY AdminBib$2026;
GRANT CREATE SESSION TO USUARIO_ADMINISTRADOR;
GRANT RESOURCE TO USUARIO_ADMINISTRADOR;

-- ASIGNACION DE LOS ROLES A LOS USUARIOS
GRANT FIDE_DOCENTE_ROL TO USUARIO_DOCENTE;
GRANT FIDE_COMISION_ROL TO USUARIO_COMISION;
GRANT FIDE_COORDINADOR_ROL TO USUARIO_COORDINADOR;
GRANT FIDE_ADMINISTRADOR_ROL TO USUARIO_ADMINISTRADOR;

-- ASIGNACION DEL PERFIL DE SEGURIDAD A LOS USUARIOS
ALTER USER USUARIO_DOCENTE PROFILE BIBLIOTECOLOGIA_PERFIL_SEGURIDAD;
ALTER USER USUARIO_COMISION PROFILE BIBLIOTECOLOGIA_PERFIL_SEGURIDAD;
ALTER USER USUARIO_COORDINADOR PROFILE BIBLIOTECOLOGIA_PERFIL_SEGURIDAD;
ALTER USER USUARIO_ADMINISTRADOR PROFILE BIBLIOTECOLOGIA_PERFIL_SEGURIDAD;
