CREATE TABLE FIDE_ESTADO_TB (
    ID_ESTADO NUMBER,
    NOMBRE VARCHAR2(50),
    DESCRIPCION VARCHAR2(250),
    CONSTRAINT FIDE_ESTADO_ID_ESTADO_PK PRIMARY KEY (ID_ESTADO)
) TABLESPACE DATA;

CREATE TABLE FIDE_TIPO_USUARIO_TB (
    ID_TIPO_USUARIO NUMBER,
    ID_ESTADO NUMBER,
    NOMBRE VARCHAR2(50),
    DESCRIPCION VARCHAR2(250),
    CONSTRAINT FIDE_TIPO_USUARIO_ID_TIPO_USUARIO_PK PRIMARY KEY (ID_TIPO_USUARIO),
    CONSTRAINT FIDE_TIPO_USUARIO_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO)
        REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
) TABLESPACE DATA;

CREATE TABLE FIDE_TIPO_SOLICITUD_TB (
    ID_TIPO_SOLICITUD NUMBER,
    ID_ESTADO NUMBER,
    NOMBRE VARCHAR2(50),
    DESCRIPCION VARCHAR2(250),
    CONSTRAINT FIDE_TIPO_SOLICITUD_ID_TIPO_SOLICITUD_PK PRIMARY KEY (ID_TIPO_SOLICITUD),
    CONSTRAINT FIDE_TIPO_SOLICITUD_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO)
        REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
) TABLESPACE DATA;

CREATE TABLE FIDE_TIPO_NOTIFICACION_TB (
    ID_TIPO_NOTIFICACION NUMBER,
    ID_ESTADO NUMBER,
    NOMBRE VARCHAR2(50),
    DESCRIPCION VARCHAR2(250),
    CONSTRAINT FIDE_TIPO_NOTIFICACION_ID_TIPO_NOTIFICACION_PK PRIMARY KEY (ID_TIPO_NOTIFICACION),
    CONSTRAINT FIDE_TIPO_NOTIFICACION_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO)
        REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
) TABLESPACE DATA;

CREATE TABLE FIDE_MODALIDAD_TB (
    ID_MODALIDAD NUMBER,
    ID_ESTADO NUMBER,
    NOMBRE VARCHAR2(50),
    CONSTRAINT FIDE_MODALIDAD_ID_MODALIDAD_PK PRIMARY KEY (ID_MODALIDAD),
    CONSTRAINT FIDE_MODALIDAD_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO)
        REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
) TABLESPACE DATA;

CREATE TABLE FIDE_ROL_TB (
    ID_ROL NUMBER,
    ID_ESTADO NUMBER,
    NOMBRE VARCHAR2(50),
    DESCRIPCION VARCHAR2(250),
    CONSTRAINT FIDE_ROL_ID_ROL_PK PRIMARY KEY (ID_ROL),
    CONSTRAINT FIDE_ROL_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO)
        REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
) TABLESPACE DATA;

CREATE TABLE FIDE_CARRERA_TB (
    ID_CARRERA NUMBER,
    ID_ESTADO NUMBER,
    NOMBRE VARCHAR2(100),
    CODIGO_CARRERA VARCHAR2(20),
    GRADO VARCHAR2(50),
    CONSTRAINT FIDE_CARRERA_ID_CARRERA_PK PRIMARY KEY (ID_CARRERA),
    CONSTRAINT FIDE_CARRERA_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO)
        REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
) TABLESPACE DATA;

CREATE TABLE FIDE_USUARIO_TB (
    CEDULA VARCHAR2(20),
    ID_TIPO_USUARIO NUMBER,
    ID_ESTADO NUMBER,
    NOMBRE VARCHAR2(50),
    APELLIDO_1 VARCHAR2(50),
    APELLIDO_2 VARCHAR2(50),
    FECHA_REGISTRO DATE,
    CONSTRAINT FIDE_USUARIO_CEDULA_PK PRIMARY KEY (CEDULA),
    CONSTRAINT FIDE_USUARIO_ID_TIPO_USUARIO_FK FOREIGN KEY (ID_TIPO_USUARIO)
        REFERENCES FIDE_TIPO_USUARIO_TB(ID_TIPO_USUARIO),
    CONSTRAINT FIDE_USUARIO_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO)
        REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
) TABLESPACE DATA;

CREATE TABLE FIDE_CORREO_TB (
    CEDULA VARCHAR2(20),
    CORREO VARCHAR2(100),
    ID_ESTADO NUMBER,
    CONSTRAINT FIDE_CORREO_CEDULA_CORREO_PK PRIMARY KEY (CEDULA, CORREO),
    CONSTRAINT FIDE_CORREO_CEDULA_FK FOREIGN KEY (CEDULA)
        REFERENCES FIDE_USUARIO_TB(CEDULA),
    CONSTRAINT FIDE_CORREO_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO)
        REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
) TABLESPACE DATA;

CREATE TABLE FIDE_TELEFONO_TB (
    CEDULA VARCHAR2(20),
    TELEFONO VARCHAR2(20),
    ID_ESTADO NUMBER,
    CONSTRAINT FIDE_TELEFONO_CEDULA_TELEFONO_PK PRIMARY KEY (CEDULA, TELEFONO),
    CONSTRAINT FIDE_TELEFONO_CEDULA_FK FOREIGN KEY (CEDULA)
        REFERENCES FIDE_USUARIO_TB(CEDULA),
    CONSTRAINT FIDE_TELEFONO_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO)
        REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
) TABLESPACE DATA;

CREATE TABLE FIDE_CURSO_TB (
    ID_CURSO NUMBER,
    ID_ESTADO NUMBER,
    CODIGO_CURSO VARCHAR2(20),
    NOMBRE_CURSO VARCHAR2(100),
    CREDITOS NUMBER,
    HORAS NUMBER,
    CONSTRAINT FIDE_CURSO_ID_CURSO_PK PRIMARY KEY (ID_CURSO),
    CONSTRAINT FIDE_CURSO_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO)
        REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
) TABLESPACE DATA;

CREATE TABLE FIDE_CURSO_CARRERA_TB (
    ID_CURSO NUMBER,
    ID_CARRERA NUMBER,
    TIPO VARCHAR2(50),
    CICLO VARCHAR2(20),
    CONSTRAINT FIDE_CURSO_CARRERA_ID_CURSO_ID_CARRERA_PK PRIMARY KEY (ID_CURSO, ID_CARRERA),
    CONSTRAINT FIDE_CURSO_CARRERA_ID_CURSO_FK FOREIGN KEY (ID_CURSO)
        REFERENCES FIDE_CURSO_TB(ID_CURSO),
    CONSTRAINT FIDE_CURSO_CARRERA_ID_CARRERA_FK FOREIGN KEY (ID_CARRERA)
        REFERENCES FIDE_CARRERA_TB(ID_CARRERA)
) TABLESPACE DATA;

CREATE TABLE FIDE_PROGRAMA_TB (
    ID_PROGRAMA NUMBER,
    ID_CURSO NUMBER,
    ID_ESTADO NUMBER,
    FECHA_CREACION DATE,
    CONSTRAINT FIDE_PROGRAMA_ID_PROGRAMA_PK PRIMARY KEY (ID_PROGRAMA),
    CONSTRAINT FIDE_PROGRAMA_ID_CURSO_FK FOREIGN KEY (ID_CURSO)
        REFERENCES FIDE_CURSO_TB(ID_CURSO),
    CONSTRAINT FIDE_PROGRAMA_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO)
        REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
) TABLESPACE DATA;

CREATE TABLE FIDE_VERSION_PROGRAMA_TB (
    ID_VERSION NUMBER,
    ID_PROGRAMA NUMBER,
    ID_MODALIDAD NUMBER,
    ID_ESTADO NUMBER,
    NUMERO_VERSION NUMBER,
    FECHA_PUBLICACION DATE,
    OBSERVACIONES VARCHAR2(250),
    CONSTRAINT FIDE_VERSION_PROGRAMA_ID_VERSION_PK PRIMARY KEY (ID_VERSION),
    CONSTRAINT FIDE_VERSION_PROGRAMA_ID_PROGRAMA_FK FOREIGN KEY (ID_PROGRAMA)
        REFERENCES FIDE_PROGRAMA_TB(ID_PROGRAMA),
    CONSTRAINT FIDE_VERSION_PROGRAMA_ID_MODALIDAD_FK FOREIGN KEY (ID_MODALIDAD)
        REFERENCES FIDE_MODALIDAD_TB(ID_MODALIDAD),
    CONSTRAINT FIDE_VERSION_PROGRAMA_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO)
        REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
) TABLESPACE DATA;

CREATE TABLE FIDE_CICLO_ACADEMICO_TB (
    ID_CICLO NUMBER,
    ID_ESTADO NUMBER,
    ANIO NUMBER,
    CICLO VARCHAR2(20),
    FECHA_INICIO DATE,
    FECHA_FIN DATE,
    CONSTRAINT FIDE_CICLO_ACADEMICO_ID_CICLO_PK PRIMARY KEY (ID_CICLO),
    CONSTRAINT FIDE_CICLO_ACADEMICO_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO)
        REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
) TABLESPACE DATA;

CREATE TABLE FIDE_PERIODO_CAMBIO_TB (
    ID_PERIODO NUMBER,
    ID_CICLO NUMBER,
    ID_ESTADO NUMBER,
    FECHA_INICIO DATE,
    FECHA_FIN DATE,
    CONSTRAINT FIDE_PERIODO_CAMBIO_ID_PERIODO_PK PRIMARY KEY (ID_PERIODO),
    CONSTRAINT FIDE_PERIODO_CAMBIO_ID_CICLO_FK FOREIGN KEY (ID_CICLO)
        REFERENCES FIDE_CICLO_ACADEMICO_TB(ID_CICLO),
    CONSTRAINT FIDE_PERIODO_CAMBIO_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO)
        REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
) TABLESPACE DATA;

CREATE TABLE FIDE_SOLICITUD_TB (
    ID_SOLICITUD NUMBER,
    CEDULA VARCHAR2(20),
    ID_VERSION NUMBER,
    ID_TIPO_SOLICITUD NUMBER,
    ID_ESTADO NUMBER,
    JUSTIFICACION VARCHAR2(500),
    FECHA_SOLICITUD DATE,
    FECHA_RESPUESTA DATE,
    CONSTRAINT FIDE_SOLICITUD_ID_SOLICITUD_PK PRIMARY KEY (ID_SOLICITUD),
    CONSTRAINT FIDE_SOLICITUD_CEDULA_FK FOREIGN KEY (CEDULA)
        REFERENCES FIDE_USUARIO_TB(CEDULA),
    CONSTRAINT FIDE_SOLICITUD_ID_VERSION_FK FOREIGN KEY (ID_VERSION)
        REFERENCES FIDE_VERSION_PROGRAMA_TB(ID_VERSION),
    CONSTRAINT FIDE_SOLICITUD_ID_TIPO_SOLICITUD_FK FOREIGN KEY (ID_TIPO_SOLICITUD)
        REFERENCES FIDE_TIPO_SOLICITUD_TB(ID_TIPO_SOLICITUD),
    CONSTRAINT FIDE_SOLICITUD_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO)
        REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
) TABLESPACE DATA;

CREATE TABLE FIDE_NOTIFICACION_TB (
    ID_NOTIFICACION NUMBER,
    ID_TIPO_NOTIFICACION NUMBER,
    ID_ESTADO NUMBER,
    ASUNTO VARCHAR2(100),
    MENSAJE VARCHAR2(500),
    FECHA_ENVIO DATE,
    CONSTRAINT FIDE_NOTIFICACION_ID_NOTIFICACION_PK PRIMARY KEY (ID_NOTIFICACION),
    CONSTRAINT FIDE_NOTIFICACION_ID_TIPO_NOTIFICACION_FK FOREIGN KEY (ID_TIPO_NOTIFICACION)
        REFERENCES FIDE_TIPO_NOTIFICACION_TB(ID_TIPO_NOTIFICACION),
    CONSTRAINT FIDE_NOTIFICACION_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO)
        REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
) TABLESPACE DATA;

CREATE TABLE FIDE_OBJETIVO_TB (
    ID_OBJETIVO NUMBER,
    ID_VERSION NUMBER,
    DESCRIPCION VARCHAR2(500),
    CONSTRAINT FIDE_OBJETIVO_ID_OBJETIVO_PK PRIMARY KEY (ID_OBJETIVO),
    CONSTRAINT FIDE_OBJETIVO_ID_VERSION_FK FOREIGN KEY (ID_VERSION)
        REFERENCES FIDE_VERSION_PROGRAMA_TB(ID_VERSION)
) TABLESPACE DATA;

CREATE TABLE FIDE_CONTENIDO_TB (
    ID_CONTENIDO NUMBER,
    ID_VERSION NUMBER,
    UNIDAD VARCHAR2(100),
    TEMA VARCHAR2(150),
    DESCRIPCION VARCHAR2(500),
    CONSTRAINT FIDE_CONTENIDO_ID_CONTENIDO_PK PRIMARY KEY (ID_CONTENIDO),
    CONSTRAINT FIDE_CONTENIDO_ID_VERSION_FK FOREIGN KEY (ID_VERSION)
        REFERENCES FIDE_VERSION_PROGRAMA_TB(ID_VERSION)
) TABLESPACE DATA;

CREATE TABLE FIDE_CRONOGRAMA_TB (
    ID_CRONOGRAMA NUMBER,
    ID_VERSION NUMBER,
    SEMANA NUMBER,
    ACTIVIDAD VARCHAR2(250),
    FECHA_ESTIMADA DATE,
    CONSTRAINT FIDE_CRONOGRAMA_ID_CRONOGRAMA_PK PRIMARY KEY (ID_CRONOGRAMA),
    CONSTRAINT FIDE_CRONOGRAMA_ID_VERSION_FK FOREIGN KEY (ID_VERSION)
        REFERENCES FIDE_VERSION_PROGRAMA_TB(ID_VERSION)
) TABLESPACE DATA;

CREATE TABLE FIDE_EVALUACION_TB (
    ID_EVALUACION NUMBER,
    ID_VERSION NUMBER,
    ACTIVIDAD VARCHAR2(150),
    PORCENTAJE NUMBER(5,2),
    DESCRIPCION VARCHAR2(500),
    CONSTRAINT FIDE_EVALUACION_ID_EVALUACION_PK PRIMARY KEY (ID_EVALUACION),
    CONSTRAINT FIDE_EVALUACION_ID_VERSION_FK FOREIGN KEY (ID_VERSION)
        REFERENCES FIDE_VERSION_PROGRAMA_TB(ID_VERSION)
) TABLESPACE DATA;

CREATE TABLE FIDE_BIBLIOGRAFIA_TB (
    ID_BIBLIOGRAFIA NUMBER,
    TITULO VARCHAR2(200),
    AUTOR VARCHAR2(150),
    ANIO_PUBLICACION NUMBER,
    CONSTRAINT FIDE_BIBLIOGRAFIA_ID_BIBLIOGRAFIA_PK PRIMARY KEY (ID_BIBLIOGRAFIA)
) TABLESPACE DATA;

CREATE TABLE FIDE_VERSION_BIBLIOGRAFIA_TB (
    ID_VERSION NUMBER,
    ID_BIBLIOGRAFIA NUMBER,
    CONSTRAINT FIDE_VERSION_BIBLIOGRAFIA_ID_VERSION_ID_BIBLIOGRAFIA_PK 
        PRIMARY KEY (ID_VERSION, ID_BIBLIOGRAFIA),
    CONSTRAINT FIDE_VERSION_BIBLIOGRAFIA_ID_VERSION_FK FOREIGN KEY (ID_VERSION)
        REFERENCES FIDE_VERSION_PROGRAMA_TB(ID_VERSION),
    CONSTRAINT FIDE_VERSION_BIBLIOGRAFIA_ID_BIBLIOGRAFIA_FK FOREIGN KEY (ID_BIBLIOGRAFIA)
        REFERENCES FIDE_BIBLIOGRAFIA_TB(ID_BIBLIOGRAFIA)
) TABLESPACE DATA;

CREATE TABLE FIDE_DETALLE_SOLICITUD_TB (
    ID_DETALLE NUMBER,
    ID_SOLICITUD NUMBER,
    CAMPO_MODIFICADO VARCHAR2(100),
    VALOR_ANTERIOR VARCHAR2(500),
    VALOR_NUEVO VARCHAR2(500),
    CONSTRAINT FIDE_DETALLE_SOLICITUD_ID_DETALLE_PK PRIMARY KEY (ID_DETALLE),
    CONSTRAINT FIDE_DETALLE_SOLICITUD_ID_SOLICITUD_FK FOREIGN KEY (ID_SOLICITUD)
        REFERENCES FIDE_SOLICITUD_TB(ID_SOLICITUD)
) TABLESPACE DATA;

CREATE TABLE FIDE_NOTIFICACION_USUARIO_TB (
    CEDULA VARCHAR2(20),
    ID_NOTIFICACION NUMBER,
    CONSTRAINT FIDE_NOTIFICACION_USUARIO_CEDULA_ID_NOTIFICACION_PK 
        PRIMARY KEY (CEDULA, ID_NOTIFICACION),
    CONSTRAINT FIDE_NOTIFICACION_USUARIO_CEDULA_FK FOREIGN KEY (CEDULA)
        REFERENCES FIDE_USUARIO_TB(CEDULA),
    CONSTRAINT FIDE_NOTIFICACION_USUARIO_ID_NOTIFICACION_FK FOREIGN KEY (ID_NOTIFICACION)
        REFERENCES FIDE_NOTIFICACION_TB(ID_NOTIFICACION)
) TABLESPACE DATA;

CREATE TABLE FIDE_REVISION_SOLICITUD_TB (
    CEDULA VARCHAR2(20),
    ID_SOLICITUD NUMBER,
    ID_ESTADO NUMBER,
    COMENTARIO VARCHAR2(500),
    FECHA_REVISION DATE,
    CONSTRAINT FIDE_REVISION_SOLICITUD_CEDULA_ID_SOLICITUD_PK 
        PRIMARY KEY (CEDULA, ID_SOLICITUD),
    CONSTRAINT FIDE_REVISION_SOLICITUD_CEDULA_FK FOREIGN KEY (CEDULA)
        REFERENCES FIDE_USUARIO_TB(CEDULA),
    CONSTRAINT FIDE_REVISION_SOLICITUD_ID_SOLICITUD_FK FOREIGN KEY (ID_SOLICITUD)
        REFERENCES FIDE_SOLICITUD_TB(ID_SOLICITUD),
    CONSTRAINT FIDE_REVISION_SOLICITUD_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO)
        REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
) TABLESPACE DATA;

CREATE TABLE FIDE_USUARIO_ROL_TB (
    CEDULA VARCHAR2(20),
    ID_ROL NUMBER,
    CONSTRAINT FIDE_USUARIO_ROL_CEDULA_ID_ROL_PK PRIMARY KEY (CEDULA, ID_ROL),
    CONSTRAINT FIDE_USUARIO_ROL_CEDULA_FK FOREIGN KEY (CEDULA)
        REFERENCES FIDE_USUARIO_TB(CEDULA),
    CONSTRAINT FIDE_USUARIO_ROL_ID_ROL_FK FOREIGN KEY (ID_ROL)
        REFERENCES FIDE_ROL_TB(ID_ROL)
) TABLESPACE DATA;


-- INDEXES
CREATE INDEX FIDE_CORREO_ID_ESTADO_IDX ON FIDE_CORREO_TB (ID_ESTADO);
CREATE INDEX FIDE_TELEFONO_ID_ESTADO_IDX ON FIDE_TELEFONO_TB (ID_ESTADO);
CREATE INDEX FIDE_USUARIO_ID_TIPO_USUARIO_IDX ON FIDE_USUARIO_TB (ID_TIPO_USUARIO);
CREATE INDEX FIDE_USUARIO_ID_ESTADO_IDX ON FIDE_USUARIO_TB (ID_ESTADO);
CREATE INDEX FIDE_VERSION_PROGRAMA_ID_PROGRAMA_IDX ON FIDE_VERSION_PROGRAMA_TB (ID_PROGRAMA);
CREATE INDEX FIDE_VERSION_PROGRAMA_ID_MODALIDAD_IDX ON FIDE_VERSION_PROGRAMA_TB (ID_MODALIDAD);
CREATE INDEX FIDE_VERSION_PROGRAMA_ID_ESTADO_IDX ON FIDE_VERSION_PROGRAMA_TB (ID_ESTADO);
CREATE INDEX FIDE_PROGRAMA_ID_CURSO_IDX ON FIDE_PROGRAMA_TB (ID_CURSO);
CREATE INDEX FIDE_PROGRAMA_ID_ESTADO_IDX ON FIDE_PROGRAMA_TB (ID_ESTADO);
CREATE INDEX FIDE_PERIODO_CAMBIO_ID_CICLO_IDX ON FIDE_PERIODO_CAMBIO_TB (ID_CICLO);
CREATE INDEX FIDE_PERIODO_CAMBIO_ID_ESTADO_IDX ON FIDE_PERIODO_CAMBIO_TB (ID_ESTADO);
CREATE INDEX FIDE_SOLICITUD_CEDULA_IDX ON FIDE_SOLICITUD_TB (CEDULA);
CREATE INDEX FIDE_SOLICITUD_ID_VERSION_IDX ON FIDE_SOLICITUD_TB (ID_VERSION);
CREATE INDEX FIDE_SOLICITUD_ID_TIPO_SOLICITUD_IDX ON FIDE_SOLICITUD_TB (ID_TIPO_SOLICITUD);
CREATE INDEX FIDE_SOLICITUD_ID_ESTADO_IDX ON FIDE_SOLICITUD_TB (ID_ESTADO);
CREATE INDEX FIDE_NOTIFICACION_ID_TIPO_NOTIFICACION_IDX ON FIDE_NOTIFICACION_TB (ID_TIPO_NOTIFICACION);
CREATE INDEX FIDE_NOTIFICACION_ID_ESTADO_IDX ON FIDE_NOTIFICACION_TB (ID_ESTADO);
CREATE INDEX FIDE_TIPO_USUARIO_ID_ESTADO_IDX ON FIDE_TIPO_USUARIO_TB (ID_ESTADO);
CREATE INDEX FIDE_USUARIO_ROL_ID_ROL_IDX ON FIDE_USUARIO_ROL_TB (ID_ROL);
CREATE INDEX FIDE_TIPO_SOLICITUD_ID_ESTADO_IDX ON FIDE_TIPO_SOLICITUD_TB (ID_ESTADO);
CREATE INDEX FIDE_REVISION_SOLICITUD_ID_SOLICITUD_IDX ON FIDE_REVISION_SOLICITUD_TB (ID_SOLICITUD);
CREATE INDEX FIDE_REVISION_SOLICITUD_ID_ESTADO_IDX ON FIDE_REVISION_SOLICITUD_TB (ID_ESTADO);
CREATE INDEX FIDE_DETALLE_SOLICITUD_ID_SOLICITUD_IDX ON FIDE_DETALLE_SOLICITUD_TB (ID_SOLICITUD);
CREATE INDEX FIDE_TIPO_NOTIFICACION_ID_ESTADO_IDX ON FIDE_TIPO_NOTIFICACION_TB (ID_ESTADO);
CREATE INDEX FIDE_NOTIFICACION_USUARIO_ID_NOTIFICACION_IDX ON FIDE_NOTIFICACION_USUARIO_TB (ID_NOTIFICACION);
CREATE INDEX FIDE_OBJETIVO_ID_VERSION_IDX ON FIDE_OBJETIVO_TB (ID_VERSION);
CREATE INDEX FIDE_CONTENIDO_ID_VERSION_IDX ON FIDE_CONTENIDO_TB (ID_VERSION);
CREATE INDEX FIDE_CRONOGRAMA_ID_VERSION_IDX ON FIDE_CRONOGRAMA_TB (ID_VERSION);
CREATE INDEX FIDE_EVALUACION_ID_VERSION_IDX ON FIDE_EVALUACION_TB (ID_VERSION);
CREATE INDEX FIDE_CURSO_ID_ESTADO_IDX ON FIDE_CURSO_TB (ID_ESTADO);
CREATE INDEX FIDE_CURSO_CARRERA_ID_CARRERA_IDX ON FIDE_CURSO_CARRERA_TB (ID_CARRERA);
CREATE INDEX FIDE_CICLO_ACADEMICO_ID_ESTADO_IDX ON FIDE_CICLO_ACADEMICO_TB (ID_ESTADO);
CREATE INDEX FIDE_VERSION_BIBLIOGRAFIA_ID_BIBLIOGRAFIA_IDX ON FIDE_VERSION_BIBLIOGRAFIA_TB (ID_BIBLIOGRAFIA);
