
-- Permisos de los roles sobre las tablas FIDE_*_TB
-- Debe correrse DESPUES de crear las tablas (01_tablas_indices.sql)

-- PERMISOS DEL ROL FIDE_DOCENTE_ROL
GRANT SELECT ON SGPC_ADMIN.FIDE_ESTADO_TB TO FIDE_DOCENTE_ROL;
GRANT SELECT ON SGPC_ADMIN.FIDE_TIPO_SOLICITUD_TB TO FIDE_DOCENTE_ROL;
GRANT SELECT ON SGPC_ADMIN.FIDE_TIPO_NOTIFICACION_TB TO FIDE_DOCENTE_ROL;
GRANT SELECT ON SGPC_ADMIN.FIDE_MODALIDAD_TB TO FIDE_DOCENTE_ROL;
GRANT SELECT ON SGPC_ADMIN.FIDE_CARRERA_TB TO FIDE_DOCENTE_ROL;
GRANT SELECT ON SGPC_ADMIN.FIDE_CURSO_TB TO FIDE_DOCENTE_ROL;
GRANT SELECT ON SGPC_ADMIN.FIDE_CURSO_CARRERA_TB TO FIDE_DOCENTE_ROL;
GRANT SELECT ON SGPC_ADMIN.FIDE_PROGRAMA_TB TO FIDE_DOCENTE_ROL;
GRANT SELECT ON SGPC_ADMIN.FIDE_VERSION_PROGRAMA_TB TO FIDE_DOCENTE_ROL;
GRANT SELECT ON SGPC_ADMIN.FIDE_OBJETIVO_TB TO FIDE_DOCENTE_ROL;
GRANT SELECT ON SGPC_ADMIN.FIDE_CONTENIDO_TB TO FIDE_DOCENTE_ROL;
GRANT SELECT ON SGPC_ADMIN.FIDE_CRONOGRAMA_TB TO FIDE_DOCENTE_ROL;
GRANT SELECT ON SGPC_ADMIN.FIDE_EVALUACION_TB TO FIDE_DOCENTE_ROL;
GRANT SELECT ON SGPC_ADMIN.FIDE_BIBLIOGRAFIA_TB TO FIDE_DOCENTE_ROL;
GRANT SELECT ON SGPC_ADMIN.FIDE_VERSION_BIBLIOGRAFIA_TB TO FIDE_DOCENTE_ROL;
GRANT SELECT, INSERT ON SGPC_ADMIN.FIDE_SOLICITUD_TB TO FIDE_DOCENTE_ROL;
GRANT SELECT, INSERT ON SGPC_ADMIN.FIDE_DETALLE_SOLICITUD_TB TO FIDE_DOCENTE_ROL;
GRANT SELECT ON SGPC_ADMIN.FIDE_NOTIFICACION_TB TO FIDE_DOCENTE_ROL;
GRANT SELECT, UPDATE ON SGPC_ADMIN.FIDE_NOTIFICACION_USUARIO_TB TO FIDE_DOCENTE_ROL;

-- PERMISOS DEL ROL FIDE_COMISION_ROL
GRANT SELECT ON SGPC_ADMIN.FIDE_ESTADO_TB TO FIDE_COMISION_ROL;
GRANT SELECT ON SGPC_ADMIN.FIDE_TIPO_SOLICITUD_TB TO FIDE_COMISION_ROL;
GRANT SELECT ON SGPC_ADMIN.FIDE_TIPO_NOTIFICACION_TB TO FIDE_COMISION_ROL;
GRANT SELECT ON SGPC_ADMIN.FIDE_MODALIDAD_TB TO FIDE_COMISION_ROL;
GRANT SELECT ON SGPC_ADMIN.FIDE_CARRERA_TB TO FIDE_COMISION_ROL;
GRANT SELECT ON SGPC_ADMIN.FIDE_CURSO_TB TO FIDE_COMISION_ROL;
GRANT SELECT ON SGPC_ADMIN.FIDE_CURSO_CARRERA_TB TO FIDE_COMISION_ROL;
GRANT SELECT ON SGPC_ADMIN.FIDE_PROGRAMA_TB TO FIDE_COMISION_ROL;
GRANT SELECT ON SGPC_ADMIN.FIDE_VERSION_PROGRAMA_TB TO FIDE_COMISION_ROL;
GRANT SELECT ON SGPC_ADMIN.FIDE_OBJETIVO_TB TO FIDE_COMISION_ROL;
GRANT SELECT ON SGPC_ADMIN.FIDE_CONTENIDO_TB TO FIDE_COMISION_ROL;
GRANT SELECT ON SGPC_ADMIN.FIDE_CRONOGRAMA_TB TO FIDE_COMISION_ROL;
GRANT SELECT ON SGPC_ADMIN.FIDE_EVALUACION_TB TO FIDE_COMISION_ROL;
GRANT SELECT ON SGPC_ADMIN.FIDE_BIBLIOGRAFIA_TB TO FIDE_COMISION_ROL;
GRANT SELECT ON SGPC_ADMIN.FIDE_VERSION_BIBLIOGRAFIA_TB TO FIDE_COMISION_ROL;
GRANT SELECT, UPDATE ON SGPC_ADMIN.FIDE_SOLICITUD_TB TO FIDE_COMISION_ROL;
GRANT SELECT ON SGPC_ADMIN.FIDE_DETALLE_SOLICITUD_TB TO FIDE_COMISION_ROL;
GRANT SELECT, INSERT, UPDATE ON SGPC_ADMIN.FIDE_REVISION_SOLICITUD_TB TO FIDE_COMISION_ROL;
GRANT SELECT, INSERT ON SGPC_ADMIN.FIDE_NOTIFICACION_TB TO FIDE_COMISION_ROL;
GRANT SELECT, INSERT, UPDATE ON SGPC_ADMIN.FIDE_NOTIFICACION_USUARIO_TB TO FIDE_COMISION_ROL;

-- PERMISOS DEL ROL FIDE_COORDINADOR_ROL
GRANT SELECT ON SGPC_ADMIN.FIDE_ESTADO_TB TO FIDE_COORDINADOR_ROL;
GRANT SELECT ON SGPC_ADMIN.FIDE_TIPO_SOLICITUD_TB TO FIDE_COORDINADOR_ROL;
GRANT SELECT ON SGPC_ADMIN.FIDE_TIPO_NOTIFICACION_TB TO FIDE_COORDINADOR_ROL;
GRANT SELECT ON SGPC_ADMIN.FIDE_MODALIDAD_TB TO FIDE_COORDINADOR_ROL;
GRANT SELECT ON SGPC_ADMIN.FIDE_CARRERA_TB TO FIDE_COORDINADOR_ROL;
GRANT SELECT, INSERT, UPDATE ON SGPC_ADMIN.FIDE_CURSO_TB TO FIDE_COORDINADOR_ROL;
GRANT SELECT, INSERT, UPDATE ON SGPC_ADMIN.FIDE_CURSO_CARRERA_TB TO FIDE_COORDINADOR_ROL;
GRANT SELECT, INSERT, UPDATE ON SGPC_ADMIN.FIDE_PROGRAMA_TB TO FIDE_COORDINADOR_ROL;
GRANT SELECT, INSERT, UPDATE ON SGPC_ADMIN.FIDE_VERSION_PROGRAMA_TB TO FIDE_COORDINADOR_ROL;
GRANT SELECT, INSERT, UPDATE ON SGPC_ADMIN.FIDE_CICLO_ACADEMICO_TB TO FIDE_COORDINADOR_ROL;
GRANT SELECT, INSERT, UPDATE ON SGPC_ADMIN.FIDE_PERIODO_CAMBIO_TB TO FIDE_COORDINADOR_ROL;
GRANT SELECT, INSERT, UPDATE ON SGPC_ADMIN.FIDE_OBJETIVO_TB TO FIDE_COORDINADOR_ROL;
GRANT SELECT, INSERT, UPDATE ON SGPC_ADMIN.FIDE_CONTENIDO_TB TO FIDE_COORDINADOR_ROL;
GRANT SELECT, INSERT, UPDATE ON SGPC_ADMIN.FIDE_CRONOGRAMA_TB TO FIDE_COORDINADOR_ROL;
GRANT SELECT, INSERT, UPDATE ON SGPC_ADMIN.FIDE_EVALUACION_TB TO FIDE_COORDINADOR_ROL;
GRANT SELECT, INSERT, UPDATE ON SGPC_ADMIN.FIDE_BIBLIOGRAFIA_TB TO FIDE_COORDINADOR_ROL;
GRANT SELECT, INSERT, UPDATE ON SGPC_ADMIN.FIDE_VERSION_BIBLIOGRAFIA_TB TO FIDE_COORDINADOR_ROL;
GRANT SELECT ON SGPC_ADMIN.FIDE_SOLICITUD_TB TO FIDE_COORDINADOR_ROL;
GRANT SELECT ON SGPC_ADMIN.FIDE_DETALLE_SOLICITUD_TB TO FIDE_COORDINADOR_ROL;
GRANT SELECT ON SGPC_ADMIN.FIDE_REVISION_SOLICITUD_TB TO FIDE_COORDINADOR_ROL;
GRANT SELECT ON SGPC_ADMIN.FIDE_NOTIFICACION_TB TO FIDE_COORDINADOR_ROL;
GRANT SELECT ON SGPC_ADMIN.FIDE_NOTIFICACION_USUARIO_TB TO FIDE_COORDINADOR_ROL;

-- PERMISOS DEL ROL FIDE_ADMINISTRADOR_ROL
GRANT SELECT, INSERT, UPDATE, DELETE ON SGPC_ADMIN.FIDE_ESTADO_TB TO FIDE_ADMINISTRADOR_ROL;
GRANT SELECT, INSERT, UPDATE, DELETE ON SGPC_ADMIN.FIDE_TIPO_USUARIO_TB TO FIDE_ADMINISTRADOR_ROL;
GRANT SELECT, INSERT, UPDATE, DELETE ON SGPC_ADMIN.FIDE_TIPO_SOLICITUD_TB TO FIDE_ADMINISTRADOR_ROL;
GRANT SELECT, INSERT, UPDATE, DELETE ON SGPC_ADMIN.FIDE_TIPO_NOTIFICACION_TB TO FIDE_ADMINISTRADOR_ROL;
GRANT SELECT, INSERT, UPDATE, DELETE ON SGPC_ADMIN.FIDE_MODALIDAD_TB TO FIDE_ADMINISTRADOR_ROL;
GRANT SELECT, INSERT, UPDATE, DELETE ON SGPC_ADMIN.FIDE_ROL_TB TO FIDE_ADMINISTRADOR_ROL;
GRANT SELECT, INSERT, UPDATE, DELETE ON SGPC_ADMIN.FIDE_CARRERA_TB TO FIDE_ADMINISTRADOR_ROL;
GRANT SELECT, INSERT, UPDATE, DELETE ON SGPC_ADMIN.FIDE_USUARIO_TB TO FIDE_ADMINISTRADOR_ROL;
GRANT SELECT, INSERT, UPDATE, DELETE ON SGPC_ADMIN.FIDE_CORREO_TB TO FIDE_ADMINISTRADOR_ROL;
GRANT SELECT, INSERT, UPDATE, DELETE ON SGPC_ADMIN.FIDE_TELEFONO_TB TO FIDE_ADMINISTRADOR_ROL;
GRANT SELECT, INSERT, UPDATE, DELETE ON SGPC_ADMIN.FIDE_CURSO_TB TO FIDE_ADMINISTRADOR_ROL;
GRANT SELECT, INSERT, UPDATE, DELETE ON SGPC_ADMIN.FIDE_CURSO_CARRERA_TB TO FIDE_ADMINISTRADOR_ROL;
GRANT SELECT, INSERT, UPDATE, DELETE ON SGPC_ADMIN.FIDE_PROGRAMA_TB TO FIDE_ADMINISTRADOR_ROL;
GRANT SELECT, INSERT, UPDATE, DELETE ON SGPC_ADMIN.FIDE_VERSION_PROGRAMA_TB TO FIDE_ADMINISTRADOR_ROL;
GRANT SELECT, INSERT, UPDATE, DELETE ON SGPC_ADMIN.FIDE_CICLO_ACADEMICO_TB TO FIDE_ADMINISTRADOR_ROL;
GRANT SELECT, INSERT, UPDATE, DELETE ON SGPC_ADMIN.FIDE_PERIODO_CAMBIO_TB TO FIDE_ADMINISTRADOR_ROL;
GRANT SELECT, INSERT, UPDATE, DELETE ON SGPC_ADMIN.FIDE_SOLICITUD_TB TO FIDE_ADMINISTRADOR_ROL;
GRANT SELECT, INSERT, UPDATE, DELETE ON SGPC_ADMIN.FIDE_DETALLE_SOLICITUD_TB TO FIDE_ADMINISTRADOR_ROL;
GRANT SELECT, INSERT, UPDATE, DELETE ON SGPC_ADMIN.FIDE_REVISION_SOLICITUD_TB TO FIDE_ADMINISTRADOR_ROL;
GRANT SELECT, INSERT, UPDATE, DELETE ON SGPC_ADMIN.FIDE_NOTIFICACION_TB TO FIDE_ADMINISTRADOR_ROL;
GRANT SELECT, INSERT, UPDATE, DELETE ON SGPC_ADMIN.FIDE_NOTIFICACION_USUARIO_TB TO FIDE_ADMINISTRADOR_ROL;
GRANT SELECT, INSERT, UPDATE, DELETE ON SGPC_ADMIN.FIDE_OBJETIVO_TB TO FIDE_ADMINISTRADOR_ROL;
GRANT SELECT, INSERT, UPDATE, DELETE ON SGPC_ADMIN.FIDE_CONTENIDO_TB TO FIDE_ADMINISTRADOR_ROL;
GRANT SELECT, INSERT, UPDATE, DELETE ON SGPC_ADMIN.FIDE_CRONOGRAMA_TB TO FIDE_ADMINISTRADOR_ROL;
GRANT SELECT, INSERT, UPDATE, DELETE ON SGPC_ADMIN.FIDE_EVALUACION_TB TO FIDE_ADMINISTRADOR_ROL;
GRANT SELECT, INSERT, UPDATE, DELETE ON SGPC_ADMIN.FIDE_BIBLIOGRAFIA_TB TO FIDE_ADMINISTRADOR_ROL;
GRANT SELECT, INSERT, UPDATE, DELETE ON SGPC_ADMIN.FIDE_VERSION_BIBLIOGRAFIA_TB TO FIDE_ADMINISTRADOR_ROL;
GRANT SELECT, INSERT, UPDATE, DELETE ON SGPC_ADMIN.FIDE_USUARIO_ROL_TB TO FIDE_ADMINISTRADOR_ROL;
