-- ============================================================
-- SGPC (Sistema de Gestion de Programas de Curso) - EBCI/UCR
-- SC-504 Lenguajes de Bases de Datos - Avance 2
-- Objetos de base de datos sobre el esquema FIDE_*_TB
--
-- ORDEN DE EJECUCION:
--   PASO 1: deben correr primero el script de creacion de usuario,
--           perfil de seguridad, roles y permisos (el que ya
--           tenian armado con ADMIN_ESCUELA_BIBLIOTECOLOGIA)
--   PASO 2: luego tienen que correr el script de creacion de tablas + indices
--           (sin los INSERT, no se piden para este avance)
--   PASO 3: este script (vistas, funciones, procedimientos,
--           paquetes con cursores, triggers)
--
-- Tienen que conectarse como ADMIN_ESCUELA_BIBLIOTECOLOGIA para correr
-- los 3 scripts.

-- 1. VISTAS (10)


-- Vista 1: Programas activos con datos del curso
CREATE OR REPLACE VIEW FIDE_PROGRAMAS_ACTIVOS_V AS
SELECT p.ID_PROGRAMA,
       c.CODIGO_CURSO,
       c.NOMBRE_CURSO,
       c.CREDITOS,
       p.FECHA_CREACION,
       e.NOMBRE AS ESTADO
FROM   FIDE_PROGRAMA_TB p
JOIN   FIDE_CURSO_TB c ON p.ID_CURSO = c.ID_CURSO
JOIN   FIDE_ESTADO_TB e ON p.ID_ESTADO = e.ID_ESTADO
WHERE  e.NOMBRE = 'Activo';

-- Vista 2: Cursos agrupados por carrera
CREATE OR REPLACE VIEW FIDE_CURSOS_POR_CARRERA_V AS
SELECT ca.NOMBRE AS CARRERA,
       cu.CODIGO_CURSO,
       cu.NOMBRE_CURSO,
       cu.CREDITOS,
       cc.TIPO,
       cc.CICLO
FROM   FIDE_CURSO_CARRERA_TB cc
JOIN   FIDE_CARRERA_TB ca ON cc.ID_CARRERA = ca.ID_CARRERA
JOIN   FIDE_CURSO_TB cu ON cc.ID_CURSO = cu.ID_CURSO
ORDER BY ca.NOMBRE, cc.CICLO;

-- Vista 3: Solicitudes pendientes con datos del solicitante
CREATE OR REPLACE VIEW FIDE_SOLICITUDES_PENDIENTES_V AS
SELECT s.ID_SOLICITUD,
       u.NOMBRE || ' ' || u.APELLIDO_1 AS SOLICITANTE,
       ts.NOMBRE AS TIPO_SOLICITUD,
       s.JUSTIFICACION,
       s.FECHA_SOLICITUD
FROM   FIDE_SOLICITUD_TB s
JOIN   FIDE_USUARIO_TB u ON s.CEDULA = u.CEDULA
JOIN   FIDE_TIPO_SOLICITUD_TB ts ON s.ID_TIPO_SOLICITUD = ts.ID_TIPO_SOLICITUD
JOIN   FIDE_ESTADO_TB e ON s.ID_ESTADO = e.ID_ESTADO
WHERE  e.NOMBRE = 'Pendiente';

-- Vista 4: Solicitudes ya resueltas (aprobadas o rechazadas)
CREATE OR REPLACE VIEW FIDE_SOLICITUDES_RESUELTAS_V AS
SELECT s.ID_SOLICITUD,
       u.NOMBRE || ' ' || u.APELLIDO_1 AS SOLICITANTE,
       e.NOMBRE AS ESTADO,
       s.FECHA_SOLICITUD,
       s.FECHA_RESPUESTA
FROM   FIDE_SOLICITUD_TB s
JOIN   FIDE_USUARIO_TB u ON s.CEDULA = u.CEDULA
JOIN   FIDE_ESTADO_TB e ON s.ID_ESTADO = e.ID_ESTADO
WHERE  e.NOMBRE IN ('Aprobado', 'Rechazado')
ORDER BY s.FECHA_RESPUESTA DESC;

-- Vista 5: Version vigente de cada programa (la de mayor numero)
CREATE OR REPLACE VIEW FIDE_VERSIONES_VIGENTES_V AS
SELECT vp.ID_PROGRAMA,
       vp.ID_VERSION,
       vp.NUMERO_VERSION,
       vp.FECHA_PUBLICACION,
       m.NOMBRE AS MODALIDAD
FROM   FIDE_VERSION_PROGRAMA_TB vp
JOIN   FIDE_MODALIDAD_TB m ON vp.ID_MODALIDAD = m.ID_MODALIDAD
WHERE  vp.NUMERO_VERSION = (
           SELECT MAX(v2.NUMERO_VERSION)
           FROM   FIDE_VERSION_PROGRAMA_TB v2
           WHERE  v2.ID_PROGRAMA = vp.ID_PROGRAMA);

-- Vista 6: Notificaciones por usuario destinatario
CREATE OR REPLACE VIEW FIDE_NOTIFICACIONES_USUARIO_V AS
SELECT nu.CEDULA,
       n.ID_NOTIFICACION,
       n.ASUNTO,
       n.MENSAJE,
       n.FECHA_ENVIO
FROM   FIDE_NOTIFICACION_USUARIO_TB nu
JOIN   FIDE_NOTIFICACION_TB n ON nu.ID_NOTIFICACION = n.ID_NOTIFICACION
ORDER BY n.FECHA_ENVIO DESC;

-- Vista 7: Usuarios agrupados por rol asignado
CREATE OR REPLACE VIEW FIDE_USUARIOS_POR_ROL_V AS
SELECT r.NOMBRE AS ROL,
       u.CEDULA,
       u.NOMBRE || ' ' || u.APELLIDO_1 || ' ' || u.APELLIDO_2 AS NOMBRE_COMPLETO
FROM   FIDE_USUARIO_ROL_TB ur
JOIN   FIDE_ROL_TB r ON ur.ID_ROL = r.ID_ROL
JOIN   FIDE_USUARIO_TB u ON ur.CEDULA = u.CEDULA
ORDER BY r.NOMBRE, u.APELLIDO_1;

-- Vista 8: Revisiones hechas sobre cada solicitud
CREATE OR REPLACE VIEW FIDE_REVISIONES_SOLICITUD_V AS
SELECT rs.ID_SOLICITUD,
       u.NOMBRE || ' ' || u.APELLIDO_1 AS REVISOR,
       e.NOMBRE AS RESULTADO,
       rs.COMENTARIO,
       rs.FECHA_REVISION
FROM   FIDE_REVISION_SOLICITUD_TB rs
JOIN   FIDE_USUARIO_TB u ON rs.CEDULA = u.CEDULA
JOIN   FIDE_ESTADO_TB e ON rs.ID_ESTADO = e.ID_ESTADO
ORDER BY rs.FECHA_REVISION DESC;

-- Vista 9: Bibliografia asignada a cada version de programa
CREATE OR REPLACE VIEW FIDE_BIBLIOGRAFIA_POR_VERSION_V AS
SELECT vb.ID_VERSION,
       b.TITULO,
       b.AUTOR,
       b.ANIO_PUBLICACION
FROM   FIDE_VERSION_BIBLIOGRAFIA_TB vb
JOIN   FIDE_BIBLIOGRAFIA_TB b ON vb.ID_BIBLIOGRAFIA = b.ID_BIBLIOGRAFIA
ORDER BY vb.ID_VERSION;

-- Vista 10: Ciclos academicos con su periodo de cambio asociado
CREATE OR REPLACE VIEW FIDE_CICLOS_PERIODOS_V AS
SELECT ca.ID_CICLO,
       ca.ANIO,
       ca.CICLO,
       ca.FECHA_INICIO AS INICIO_CICLO,
       ca.FECHA_FIN AS FIN_CICLO,
       pc.FECHA_INICIO AS INICIO_PERIODO_CAMBIO,
       pc.FECHA_FIN AS FIN_PERIODO_CAMBIO
FROM   FIDE_CICLO_ACADEMICO_TB ca
LEFT JOIN FIDE_PERIODO_CAMBIO_TB pc ON ca.ID_CICLO = pc.ID_CICLO
ORDER BY ca.ANIO DESC, ca.CICLO;



-- 2. FUNCIONES (15)
--

-- Funcion 1: existe una carrera
CREATE OR REPLACE FUNCTION FIDE_CARRERA_EXISTE_FN(P_ID_CARRERA IN NUMBER)
RETURN NUMBER IS
    V_TOTAL NUMBER;
BEGIN
    SELECT COUNT(*) INTO V_TOTAL FROM FIDE_CARRERA_TB WHERE ID_CARRERA = P_ID_CARRERA;
    RETURN V_TOTAL;
END;
/

-- Funcion 2: existe un curso
CREATE OR REPLACE FUNCTION FIDE_CURSO_EXISTE_FN(P_ID_CURSO IN NUMBER)
RETURN NUMBER IS
    V_TOTAL NUMBER;
BEGIN
    SELECT COUNT(*) INTO V_TOTAL FROM FIDE_CURSO_TB WHERE ID_CURSO = P_ID_CURSO;
    RETURN V_TOTAL;
END;
/

-- Funcion 3: existe un usuario (por cedula)
CREATE OR REPLACE FUNCTION FIDE_USUARIO_EXISTE_FN(P_CEDULA IN VARCHAR2)
RETURN NUMBER IS
    V_TOTAL NUMBER;
BEGIN
    SELECT COUNT(*) INTO V_TOTAL FROM FIDE_USUARIO_TB WHERE CEDULA = P_CEDULA;
    RETURN V_TOTAL;
END;
/

-- Funcion 4: existe un programa
CREATE OR REPLACE FUNCTION FIDE_PROGRAMA_EXISTE_FN(P_ID_PROGRAMA IN NUMBER)
RETURN NUMBER IS
    V_TOTAL NUMBER;
BEGIN
    SELECT COUNT(*) INTO V_TOTAL FROM FIDE_PROGRAMA_TB WHERE ID_PROGRAMA = P_ID_PROGRAMA;
    RETURN V_TOTAL;
END;
/

-- Funcion 5: existe una solicitud
CREATE OR REPLACE FUNCTION FIDE_SOLICITUD_EXISTE_FN(P_ID_SOLICITUD IN NUMBER)
RETURN NUMBER IS
    V_TOTAL NUMBER;
BEGIN
    SELECT COUNT(*) INTO V_TOTAL FROM FIDE_SOLICITUD_TB WHERE ID_SOLICITUD = P_ID_SOLICITUD;
    RETURN V_TOTAL;
END;
/

-- Funcion 6: existe una notificacion
CREATE OR REPLACE FUNCTION FIDE_NOTIFICACION_EXISTE_FN(P_ID_NOTIFICACION IN NUMBER)
RETURN NUMBER IS
    V_TOTAL NUMBER;
BEGIN
    SELECT COUNT(*) INTO V_TOTAL FROM FIDE_NOTIFICACION_TB WHERE ID_NOTIFICACION = P_ID_NOTIFICACION;
    RETURN V_TOTAL;
END;
/

-- Funcion 7: total de cursos asignados a una carrera
CREATE OR REPLACE FUNCTION FIDE_CARRERA_TOTAL_CURSOS_FN(P_ID_CARRERA IN NUMBER)
RETURN NUMBER IS
    V_TOTAL NUMBER;
BEGIN
    SELECT COUNT(*) INTO V_TOTAL FROM FIDE_CURSO_CARRERA_TB WHERE ID_CARRERA = P_ID_CARRERA;
    RETURN V_TOTAL;
END;
/

-- Funcion 8: numero de la version vigente de un programa
CREATE OR REPLACE FUNCTION FIDE_PROGRAMA_VERSION_VIGENTE_FN(P_ID_PROGRAMA IN NUMBER)
RETURN NUMBER IS
    V_VERSION NUMBER;
BEGIN
    SELECT MAX(NUMERO_VERSION) INTO V_VERSION
    FROM   FIDE_VERSION_PROGRAMA_TB
    WHERE  ID_PROGRAMA = P_ID_PROGRAMA;
    RETURN NVL(V_VERSION, 0);
END;
/

-- Funcion 9: total de solicitudes pendientes de un docente
CREATE OR REPLACE FUNCTION FIDE_DOCENTE_SOLICITUDES_PENDIENTES_FN(P_CEDULA IN VARCHAR2)
RETURN NUMBER IS
    V_TOTAL NUMBER;
BEGIN
    SELECT COUNT(*) INTO V_TOTAL
    FROM   FIDE_SOLICITUD_TB s
    JOIN   FIDE_ESTADO_TB e ON s.ID_ESTADO = e.ID_ESTADO
    WHERE  s.CEDULA = P_CEDULA
    AND    e.NOMBRE = 'Pendiente';
    RETURN V_TOTAL;
END;
/

-- Funcion 10: verificar si un ciclo academico esta activo
CREATE OR REPLACE FUNCTION FIDE_CICLO_ACTIVO_FN(P_ID_CICLO IN NUMBER)
RETURN CHAR IS
    V_NOMBRE VARCHAR2(50);
BEGIN
    SELECT e.NOMBRE INTO V_NOMBRE
    FROM   FIDE_CICLO_ACADEMICO_TB c
    JOIN   FIDE_ESTADO_TB e ON c.ID_ESTADO = e.ID_ESTADO
    WHERE  c.ID_CICLO = P_ID_CICLO;
    IF V_NOMBRE = 'Activo' THEN RETURN 'S'; ELSE RETURN 'N'; END IF;
EXCEPTION WHEN NO_DATA_FOUND THEN RETURN 'N';
END;
/

-- Funcion 11: obtener el nombre de un estado por su id
CREATE OR REPLACE FUNCTION FIDE_ESTADO_NOMBRE_FN(P_ID_ESTADO IN NUMBER)
RETURN VARCHAR2 IS
    V_NOMBRE VARCHAR2(50);
BEGIN
    SELECT NOMBRE INTO V_NOMBRE FROM FIDE_ESTADO_TB WHERE ID_ESTADO = P_ID_ESTADO;
    RETURN V_NOMBRE;
EXCEPTION WHEN NO_DATA_FOUND THEN RETURN 'DESCONOCIDO';
END;
/

-- Funcion 12: verificar si un usuario tiene un rol especifico
CREATE OR REPLACE FUNCTION FIDE_USUARIO_TIENE_ROL_FN(P_CEDULA IN VARCHAR2, P_ID_ROL IN NUMBER)
RETURN CHAR IS
    V_TOTAL NUMBER;
BEGIN
    SELECT COUNT(*) INTO V_TOTAL FROM FIDE_USUARIO_ROL_TB
    WHERE CEDULA = P_CEDULA AND ID_ROL = P_ID_ROL;
    IF V_TOTAL > 0 THEN RETURN 'S'; ELSE RETURN 'N'; END IF;
END;
/

-- Funcion 13: verificar si un periodo de cambio esta activo (estado)
CREATE OR REPLACE FUNCTION FIDE_PERIODO_ACTIVO_FN(P_ID_PERIODO IN NUMBER)
RETURN CHAR IS
    V_NOMBRE VARCHAR2(50);
BEGIN
    SELECT e.NOMBRE INTO V_NOMBRE
    FROM   FIDE_PERIODO_CAMBIO_TB p
    JOIN   FIDE_ESTADO_TB e ON p.ID_ESTADO = e.ID_ESTADO
    WHERE  p.ID_PERIODO = P_ID_PERIODO;
    IF V_NOMBRE = 'Activo' THEN RETURN 'S'; ELSE RETURN 'N'; END IF;
EXCEPTION WHEN NO_DATA_FOUND THEN RETURN 'N';
END;
/

-- Funcion 14: total de objetivos definidos para una version de programa
CREATE OR REPLACE FUNCTION FIDE_VERSION_TOTAL_OBJETIVOS_FN(P_ID_VERSION IN NUMBER)
RETURN NUMBER IS
    V_TOTAL NUMBER;
BEGIN
    SELECT COUNT(*) INTO V_TOTAL FROM FIDE_OBJETIVO_TB WHERE ID_VERSION = P_ID_VERSION;
    RETURN V_TOTAL;
END;
/

-- Funcion 15: obtener el primer correo registrado de un usuario
CREATE OR REPLACE FUNCTION FIDE_USUARIO_CORREO_PRINCIPAL_FN(P_CEDULA IN VARCHAR2)
RETURN VARCHAR2 IS
    V_CORREO VARCHAR2(100);
BEGIN
    SELECT MIN(CORREO) INTO V_CORREO FROM FIDE_CORREO_TB WHERE CEDULA = P_CEDULA;
    RETURN V_CORREO;
EXCEPTION WHEN NO_DATA_FOUND THEN RETURN NULL;
END;
/



-- 3. PROCEDIMIENTOS ALMACENADOS - CRUD (30, 5 por tabla x 6 tablas)


-- ===================== CRUD: FIDE_CARRERA_TB =====================

CREATE OR REPLACE PROCEDURE FIDE_CARRERA_INSERTAR_SP(
    P_ID_CARRERA IN NUMBER, P_ID_ESTADO IN NUMBER, P_NOMBRE IN VARCHAR2,
    P_CODIGO_CARRERA IN VARCHAR2, P_GRADO IN VARCHAR2)
IS
BEGIN
    INSERT INTO FIDE_CARRERA_TB (ID_CARRERA, ID_ESTADO, NOMBRE, CODIGO_CARRERA, GRADO)
    VALUES (P_ID_CARRERA, P_ID_ESTADO, P_NOMBRE, P_CODIGO_CARRERA, P_GRADO);
    COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE FIDE_CARRERA_LISTAR_SP(P_CURSOR OUT SYS_REFCURSOR)
IS
BEGIN
    OPEN P_CURSOR FOR SELECT ID_CARRERA, ID_ESTADO, NOMBRE, CODIGO_CARRERA, GRADO
                       FROM FIDE_CARRERA_TB ORDER BY NOMBRE;
END;
/

CREATE OR REPLACE PROCEDURE FIDE_CARRERA_BUSCAR_SP(P_ID_CARRERA IN NUMBER, P_CURSOR OUT SYS_REFCURSOR)
IS
BEGIN
    OPEN P_CURSOR FOR SELECT ID_CARRERA, ID_ESTADO, NOMBRE, CODIGO_CARRERA, GRADO
                       FROM FIDE_CARRERA_TB WHERE ID_CARRERA = P_ID_CARRERA;
END;
/

CREATE OR REPLACE PROCEDURE FIDE_CARRERA_ACTUALIZAR_SP(
    P_ID_CARRERA IN NUMBER, P_ID_ESTADO IN NUMBER, P_NOMBRE IN VARCHAR2,
    P_CODIGO_CARRERA IN VARCHAR2, P_GRADO IN VARCHAR2)
IS
BEGIN
    IF FIDE_CARRERA_EXISTE_FN(P_ID_CARRERA) = 1 THEN
        UPDATE FIDE_CARRERA_TB
        SET ID_ESTADO = P_ID_ESTADO, NOMBRE = P_NOMBRE,
            CODIGO_CARRERA = P_CODIGO_CARRERA, GRADO = P_GRADO
        WHERE ID_CARRERA = P_ID_CARRERA;
        COMMIT;
    ELSE
        RAISE_APPLICATION_ERROR(-20001, 'La carrera no existe.');
    END IF;
END;
/

CREATE OR REPLACE PROCEDURE FIDE_CARRERA_ELIMINAR_SP(P_ID_CARRERA IN NUMBER)
IS
BEGIN
    IF FIDE_CARRERA_EXISTE_FN(P_ID_CARRERA) = 1 THEN
        DELETE FROM FIDE_CARRERA_TB WHERE ID_CARRERA = P_ID_CARRERA;
        COMMIT;
    ELSE
        RAISE_APPLICATION_ERROR(-20002, 'La carrera no existe.');
    END IF;
END;
/

-- ===================== CRUD: FIDE_CURSO_TB =====================

CREATE OR REPLACE PROCEDURE FIDE_CURSO_INSERTAR_SP(
    P_ID_CURSO IN NUMBER, P_ID_ESTADO IN NUMBER, P_CODIGO_CURSO IN VARCHAR2,
    P_NOMBRE_CURSO IN VARCHAR2, P_CREDITOS IN NUMBER, P_HORAS IN NUMBER)
IS
BEGIN
    INSERT INTO FIDE_CURSO_TB (ID_CURSO, ID_ESTADO, CODIGO_CURSO, NOMBRE_CURSO, CREDITOS, HORAS)
    VALUES (P_ID_CURSO, P_ID_ESTADO, P_CODIGO_CURSO, P_NOMBRE_CURSO, P_CREDITOS, P_HORAS);
    COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE FIDE_CURSO_LISTAR_SP(P_CURSOR OUT SYS_REFCURSOR)
IS
BEGIN
    OPEN P_CURSOR FOR SELECT ID_CURSO, ID_ESTADO, CODIGO_CURSO, NOMBRE_CURSO, CREDITOS, HORAS
                       FROM FIDE_CURSO_TB ORDER BY CODIGO_CURSO;
END;
/

CREATE OR REPLACE PROCEDURE FIDE_CURSO_BUSCAR_SP(P_ID_CURSO IN NUMBER, P_CURSOR OUT SYS_REFCURSOR)
IS
BEGIN
    OPEN P_CURSOR FOR SELECT ID_CURSO, ID_ESTADO, CODIGO_CURSO, NOMBRE_CURSO, CREDITOS, HORAS
                       FROM FIDE_CURSO_TB WHERE ID_CURSO = P_ID_CURSO;
END;
/

CREATE OR REPLACE PROCEDURE FIDE_CURSO_ACTUALIZAR_SP(
    P_ID_CURSO IN NUMBER, P_ID_ESTADO IN NUMBER, P_CODIGO_CURSO IN VARCHAR2,
    P_NOMBRE_CURSO IN VARCHAR2, P_CREDITOS IN NUMBER, P_HORAS IN NUMBER)
IS
BEGIN
    IF FIDE_CURSO_EXISTE_FN(P_ID_CURSO) = 1 THEN
        UPDATE FIDE_CURSO_TB
        SET ID_ESTADO = P_ID_ESTADO, CODIGO_CURSO = P_CODIGO_CURSO,
            NOMBRE_CURSO = P_NOMBRE_CURSO, CREDITOS = P_CREDITOS, HORAS = P_HORAS
        WHERE ID_CURSO = P_ID_CURSO;
        COMMIT;
    ELSE
        RAISE_APPLICATION_ERROR(-20003, 'El curso no existe.');
    END IF;
END;
/

CREATE OR REPLACE PROCEDURE FIDE_CURSO_ELIMINAR_SP(P_ID_CURSO IN NUMBER)
IS
BEGIN
    IF FIDE_CURSO_EXISTE_FN(P_ID_CURSO) = 1 THEN
        DELETE FROM FIDE_CURSO_TB WHERE ID_CURSO = P_ID_CURSO;
        COMMIT;
    ELSE
        RAISE_APPLICATION_ERROR(-20004, 'El curso no existe.');
    END IF;
END;
/

-- ===================== CRUD: FIDE_USUARIO_TB =====================

CREATE OR REPLACE PROCEDURE FIDE_USUARIO_INSERTAR_SP(
    P_CEDULA IN VARCHAR2, P_ID_TIPO_USUARIO IN NUMBER, P_ID_ESTADO IN NUMBER,
    P_NOMBRE IN VARCHAR2, P_APELLIDO_1 IN VARCHAR2, P_APELLIDO_2 IN VARCHAR2)
IS
BEGIN
    IF FIDE_USUARIO_EXISTE_FN(P_CEDULA) = 0 THEN
        INSERT INTO FIDE_USUARIO_TB
            (CEDULA, ID_TIPO_USUARIO, ID_ESTADO, NOMBRE, APELLIDO_1, APELLIDO_2, FECHA_REGISTRO)
        VALUES
            (P_CEDULA, P_ID_TIPO_USUARIO, P_ID_ESTADO, P_NOMBRE, P_APELLIDO_1, P_APELLIDO_2, SYSDATE);
        COMMIT;
    ELSE
        RAISE_APPLICATION_ERROR(-20005, 'Ya existe un usuario con esa cedula.');
    END IF;
END;
/

CREATE OR REPLACE PROCEDURE FIDE_USUARIO_LISTAR_SP(P_CURSOR OUT SYS_REFCURSOR)
IS
BEGIN
    OPEN P_CURSOR FOR SELECT CEDULA, ID_TIPO_USUARIO, ID_ESTADO, NOMBRE, APELLIDO_1, APELLIDO_2, FECHA_REGISTRO
                       FROM FIDE_USUARIO_TB ORDER BY APELLIDO_1;
END;
/

CREATE OR REPLACE PROCEDURE FIDE_USUARIO_BUSCAR_SP(P_CEDULA IN VARCHAR2, P_CURSOR OUT SYS_REFCURSOR)
IS
BEGIN
    OPEN P_CURSOR FOR SELECT CEDULA, ID_TIPO_USUARIO, ID_ESTADO, NOMBRE, APELLIDO_1, APELLIDO_2, FECHA_REGISTRO
                       FROM FIDE_USUARIO_TB WHERE CEDULA = P_CEDULA;
END;
/

CREATE OR REPLACE PROCEDURE FIDE_USUARIO_ACTUALIZAR_SP(
    P_CEDULA IN VARCHAR2, P_ID_TIPO_USUARIO IN NUMBER, P_ID_ESTADO IN NUMBER,
    P_NOMBRE IN VARCHAR2, P_APELLIDO_1 IN VARCHAR2, P_APELLIDO_2 IN VARCHAR2)
IS
BEGIN
    IF FIDE_USUARIO_EXISTE_FN(P_CEDULA) = 1 THEN
        UPDATE FIDE_USUARIO_TB
        SET ID_TIPO_USUARIO = P_ID_TIPO_USUARIO, ID_ESTADO = P_ID_ESTADO,
            NOMBRE = P_NOMBRE, APELLIDO_1 = P_APELLIDO_1, APELLIDO_2 = P_APELLIDO_2
        WHERE CEDULA = P_CEDULA;
        COMMIT;
    ELSE
        RAISE_APPLICATION_ERROR(-20006, 'El usuario no existe.');
    END IF;
END;
/

CREATE OR REPLACE PROCEDURE FIDE_USUARIO_ELIMINAR_SP(P_CEDULA IN VARCHAR2)
IS
BEGIN
    IF FIDE_USUARIO_EXISTE_FN(P_CEDULA) = 1 THEN
        DELETE FROM FIDE_USUARIO_TB WHERE CEDULA = P_CEDULA;
        COMMIT;
    ELSE
        RAISE_APPLICATION_ERROR(-20007, 'El usuario no existe.');
    END IF;
END;
/

-- ===================== CRUD: FIDE_PROGRAMA_TB =====================

CREATE OR REPLACE PROCEDURE FIDE_PROGRAMA_INSERTAR_SP(
    P_ID_PROGRAMA IN NUMBER, P_ID_CURSO IN NUMBER, P_ID_ESTADO IN NUMBER)
IS
BEGIN
    INSERT INTO FIDE_PROGRAMA_TB (ID_PROGRAMA, ID_CURSO, ID_ESTADO, FECHA_CREACION)
    VALUES (P_ID_PROGRAMA, P_ID_CURSO, P_ID_ESTADO, SYSDATE);
    COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE FIDE_PROGRAMA_LISTAR_SP(P_CURSOR OUT SYS_REFCURSOR)
IS
BEGIN
    OPEN P_CURSOR FOR SELECT ID_PROGRAMA, ID_CURSO, ID_ESTADO, FECHA_CREACION
                       FROM FIDE_PROGRAMA_TB ORDER BY FECHA_CREACION DESC;
END;
/

CREATE OR REPLACE PROCEDURE FIDE_PROGRAMA_BUSCAR_SP(P_ID_PROGRAMA IN NUMBER, P_CURSOR OUT SYS_REFCURSOR)
IS
BEGIN
    OPEN P_CURSOR FOR SELECT ID_PROGRAMA, ID_CURSO, ID_ESTADO, FECHA_CREACION
                       FROM FIDE_PROGRAMA_TB WHERE ID_PROGRAMA = P_ID_PROGRAMA;
END;
/

CREATE OR REPLACE PROCEDURE FIDE_PROGRAMA_ACTUALIZAR_SP(
    P_ID_PROGRAMA IN NUMBER, P_ID_CURSO IN NUMBER, P_ID_ESTADO IN NUMBER)
IS
BEGIN
    IF FIDE_PROGRAMA_EXISTE_FN(P_ID_PROGRAMA) = 1 THEN
        UPDATE FIDE_PROGRAMA_TB
        SET ID_CURSO = P_ID_CURSO, ID_ESTADO = P_ID_ESTADO
        WHERE ID_PROGRAMA = P_ID_PROGRAMA;
        COMMIT;
    ELSE
        RAISE_APPLICATION_ERROR(-20008, 'El programa no existe.');
    END IF;
END;
/

CREATE OR REPLACE PROCEDURE FIDE_PROGRAMA_ELIMINAR_SP(P_ID_PROGRAMA IN NUMBER)
IS
BEGIN
    IF FIDE_PROGRAMA_EXISTE_FN(P_ID_PROGRAMA) = 1 THEN
        DELETE FROM FIDE_PROGRAMA_TB WHERE ID_PROGRAMA = P_ID_PROGRAMA;
        COMMIT;
    ELSE
        RAISE_APPLICATION_ERROR(-20009, 'El programa no existe.');
    END IF;
END;
/

-- ===================== CRUD: FIDE_SOLICITUD_TB =====================

CREATE OR REPLACE PROCEDURE FIDE_SOLICITUD_INSERTAR_SP(
    P_ID_SOLICITUD IN NUMBER, P_CEDULA IN VARCHAR2, P_ID_VERSION IN NUMBER,
    P_ID_TIPO_SOLICITUD IN NUMBER, P_ID_ESTADO IN NUMBER, P_JUSTIFICACION IN VARCHAR2)
IS
BEGIN
    INSERT INTO FIDE_SOLICITUD_TB
        (ID_SOLICITUD, CEDULA, ID_VERSION, ID_TIPO_SOLICITUD, ID_ESTADO, JUSTIFICACION, FECHA_SOLICITUD)
    VALUES
        (P_ID_SOLICITUD, P_CEDULA, P_ID_VERSION, P_ID_TIPO_SOLICITUD, P_ID_ESTADO, P_JUSTIFICACION, SYSDATE);
    COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE FIDE_SOLICITUD_LISTAR_SP(P_CURSOR OUT SYS_REFCURSOR)
IS
BEGIN
    OPEN P_CURSOR FOR SELECT ID_SOLICITUD, CEDULA, ID_VERSION, ID_TIPO_SOLICITUD, ID_ESTADO,
                              JUSTIFICACION, FECHA_SOLICITUD, FECHA_RESPUESTA
                       FROM FIDE_SOLICITUD_TB ORDER BY FECHA_SOLICITUD DESC;
END;
/

CREATE OR REPLACE PROCEDURE FIDE_SOLICITUD_BUSCAR_SP(P_ID_SOLICITUD IN NUMBER, P_CURSOR OUT SYS_REFCURSOR)
IS
BEGIN
    OPEN P_CURSOR FOR SELECT ID_SOLICITUD, CEDULA, ID_VERSION, ID_TIPO_SOLICITUD, ID_ESTADO,
                              JUSTIFICACION, FECHA_SOLICITUD, FECHA_RESPUESTA
                       FROM FIDE_SOLICITUD_TB WHERE ID_SOLICITUD = P_ID_SOLICITUD;
END;
/

CREATE OR REPLACE PROCEDURE FIDE_SOLICITUD_ACTUALIZAR_SP(
    P_ID_SOLICITUD IN NUMBER, P_ID_ESTADO IN NUMBER, P_FECHA_RESPUESTA IN DATE)
IS
BEGIN
    IF FIDE_SOLICITUD_EXISTE_FN(P_ID_SOLICITUD) = 1 THEN
        UPDATE FIDE_SOLICITUD_TB
        SET ID_ESTADO = P_ID_ESTADO, FECHA_RESPUESTA = P_FECHA_RESPUESTA
        WHERE ID_SOLICITUD = P_ID_SOLICITUD;
        COMMIT;
    ELSE
        RAISE_APPLICATION_ERROR(-20010, 'La solicitud no existe.');
    END IF;
END;
/

CREATE OR REPLACE PROCEDURE FIDE_SOLICITUD_ELIMINAR_SP(P_ID_SOLICITUD IN NUMBER)
IS
BEGIN
    IF FIDE_SOLICITUD_EXISTE_FN(P_ID_SOLICITUD) = 1 THEN
        DELETE FROM FIDE_SOLICITUD_TB WHERE ID_SOLICITUD = P_ID_SOLICITUD;
        COMMIT;
    ELSE
        RAISE_APPLICATION_ERROR(-20011, 'La solicitud no existe.');
    END IF;
END;
/

-- ===================== CRUD: FIDE_NOTIFICACION_TB =====================

CREATE OR REPLACE PROCEDURE FIDE_NOTIFICACION_INSERTAR_SP(
    P_ID_NOTIFICACION IN NUMBER, P_ID_TIPO_NOTIFICACION IN NUMBER, P_ID_ESTADO IN NUMBER,
    P_ASUNTO IN VARCHAR2, P_MENSAJE IN VARCHAR2)
IS
BEGIN
    INSERT INTO FIDE_NOTIFICACION_TB
        (ID_NOTIFICACION, ID_TIPO_NOTIFICACION, ID_ESTADO, ASUNTO, MENSAJE, FECHA_ENVIO)
    VALUES
        (P_ID_NOTIFICACION, P_ID_TIPO_NOTIFICACION, P_ID_ESTADO, P_ASUNTO, P_MENSAJE, SYSDATE);
    COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE FIDE_NOTIFICACION_LISTAR_SP(P_CURSOR OUT SYS_REFCURSOR)
IS
BEGIN
    OPEN P_CURSOR FOR SELECT ID_NOTIFICACION, ID_TIPO_NOTIFICACION, ID_ESTADO, ASUNTO, MENSAJE, FECHA_ENVIO
                       FROM FIDE_NOTIFICACION_TB ORDER BY FECHA_ENVIO DESC;
END;
/

CREATE OR REPLACE PROCEDURE FIDE_NOTIFICACION_BUSCAR_SP(P_ID_NOTIFICACION IN NUMBER, P_CURSOR OUT SYS_REFCURSOR)
IS
BEGIN
    OPEN P_CURSOR FOR SELECT ID_NOTIFICACION, ID_TIPO_NOTIFICACION, ID_ESTADO, ASUNTO, MENSAJE, FECHA_ENVIO
                       FROM FIDE_NOTIFICACION_TB WHERE ID_NOTIFICACION = P_ID_NOTIFICACION;
END;
/

CREATE OR REPLACE PROCEDURE FIDE_NOTIFICACION_ACTUALIZAR_SP(
    P_ID_NOTIFICACION IN NUMBER, P_ASUNTO IN VARCHAR2, P_MENSAJE IN VARCHAR2)
IS
BEGIN
    IF FIDE_NOTIFICACION_EXISTE_FN(P_ID_NOTIFICACION) = 1 THEN
        UPDATE FIDE_NOTIFICACION_TB
        SET ASUNTO = P_ASUNTO, MENSAJE = P_MENSAJE
        WHERE ID_NOTIFICACION = P_ID_NOTIFICACION;
        COMMIT;
    ELSE
        RAISE_APPLICATION_ERROR(-20012, 'La notificacion no existe.');
    END IF;
END;
/

CREATE OR REPLACE PROCEDURE FIDE_NOTIFICACION_ELIMINAR_SP(P_ID_NOTIFICACION IN NUMBER)
IS
BEGIN
    IF FIDE_NOTIFICACION_EXISTE_FN(P_ID_NOTIFICACION) = 1 THEN
        DELETE FROM FIDE_NOTIFICACION_TB WHERE ID_NOTIFICACION = P_ID_NOTIFICACION;
        COMMIT;
    ELSE
        RAISE_APPLICATION_ERROR(-20013, 'La notificacion no existe.');
    END IF;
END;
/



-- 4. PAQUETES CON CURSORES (10 paquetes / 15 cursores)


-- Paquete 1: FIDE_CARRERA_PKG (1 cursor)
CREATE OR REPLACE PACKAGE FIDE_CARRERA_PKG AS
    PROCEDURE CARRERAS_ACTIVAS_PRC;
END FIDE_CARRERA_PKG;
/
CREATE OR REPLACE PACKAGE BODY FIDE_CARRERA_PKG AS
    PROCEDURE CARRERAS_ACTIVAS_PRC IS
        CURSOR C_CARRERAS_ACTIVAS IS
            SELECT ca.ID_CARRERA, ca.NOMBRE
            FROM   FIDE_CARRERA_TB ca
            JOIN   FIDE_ESTADO_TB e ON ca.ID_ESTADO = e.ID_ESTADO
            WHERE  e.NOMBRE = 'Activo';
        V_ID FIDE_CARRERA_TB.ID_CARRERA%TYPE;
        V_NOMBRE FIDE_CARRERA_TB.NOMBRE%TYPE;
    BEGIN
        OPEN C_CARRERAS_ACTIVAS;
        LOOP
            FETCH C_CARRERAS_ACTIVAS INTO V_ID, V_NOMBRE;
            EXIT WHEN C_CARRERAS_ACTIVAS%NOTFOUND;
        END LOOP;
        CLOSE C_CARRERAS_ACTIVAS;
    END CARRERAS_ACTIVAS_PRC;
END FIDE_CARRERA_PKG;
/

-- Paquete 2: FIDE_CURSO_PKG (2 cursores)
CREATE OR REPLACE PACKAGE FIDE_CURSO_PKG AS
    PROCEDURE CURSOS_POR_CARRERA_PRC(CP_ID_CARRERA IN NUMBER);
    PROCEDURE CURSOS_SIN_PROGRAMA_PRC;
END FIDE_CURSO_PKG;
/
CREATE OR REPLACE PACKAGE BODY FIDE_CURSO_PKG AS
    PROCEDURE CURSOS_POR_CARRERA_PRC(CP_ID_CARRERA IN NUMBER) IS
        CURSOR C_CURSOS_CARRERA(P_ID_CARRERA NUMBER) IS
            SELECT c.ID_CURSO, c.NOMBRE_CURSO
            FROM   FIDE_CURSO_CARRERA_TB cc
            JOIN   FIDE_CURSO_TB c ON cc.ID_CURSO = c.ID_CURSO
            WHERE  cc.ID_CARRERA = P_ID_CARRERA;
        V_ID FIDE_CURSO_TB.ID_CURSO%TYPE;
        V_NOMBRE FIDE_CURSO_TB.NOMBRE_CURSO%TYPE;
    BEGIN
        OPEN C_CURSOS_CARRERA(CP_ID_CARRERA);
        LOOP
            FETCH C_CURSOS_CARRERA INTO V_ID, V_NOMBRE;
            EXIT WHEN C_CURSOS_CARRERA%NOTFOUND;
        END LOOP;
        CLOSE C_CURSOS_CARRERA;
    END CURSOS_POR_CARRERA_PRC;

    PROCEDURE CURSOS_SIN_PROGRAMA_PRC IS
        CURSOR C_SIN_PROGRAMA IS
            SELECT c.ID_CURSO, c.NOMBRE_CURSO
            FROM   FIDE_CURSO_TB c
            WHERE  c.ID_CURSO NOT IN (SELECT p.ID_CURSO FROM FIDE_PROGRAMA_TB p);
        V_ID FIDE_CURSO_TB.ID_CURSO%TYPE;
        V_NOMBRE FIDE_CURSO_TB.NOMBRE_CURSO%TYPE;
    BEGIN
        OPEN C_SIN_PROGRAMA;
        LOOP
            FETCH C_SIN_PROGRAMA INTO V_ID, V_NOMBRE;
            EXIT WHEN C_SIN_PROGRAMA%NOTFOUND;
        END LOOP;
        CLOSE C_SIN_PROGRAMA;
    END CURSOS_SIN_PROGRAMA_PRC;
END FIDE_CURSO_PKG;
/

-- Paquete 3: FIDE_USUARIO_PKG (2 cursores)
CREATE OR REPLACE PACKAGE FIDE_USUARIO_PKG AS
    PROCEDURE USUARIOS_POR_ROL_PRC(CP_ID_ROL IN NUMBER);
    PROCEDURE USUARIOS_INACTIVOS_PRC;
END FIDE_USUARIO_PKG;
/
CREATE OR REPLACE PACKAGE BODY FIDE_USUARIO_PKG AS
    PROCEDURE USUARIOS_POR_ROL_PRC(CP_ID_ROL IN NUMBER) IS
        CURSOR C_USUARIOS_ROL(P_ID_ROL NUMBER) IS
            SELECT u.CEDULA, u.NOMBRE
            FROM   FIDE_USUARIO_ROL_TB ur
            JOIN   FIDE_USUARIO_TB u ON ur.CEDULA = u.CEDULA
            WHERE  ur.ID_ROL = P_ID_ROL;
        V_CEDULA FIDE_USUARIO_TB.CEDULA%TYPE;
        V_NOMBRE FIDE_USUARIO_TB.NOMBRE%TYPE;
    BEGIN
        OPEN C_USUARIOS_ROL(CP_ID_ROL);
        LOOP
            FETCH C_USUARIOS_ROL INTO V_CEDULA, V_NOMBRE;
            EXIT WHEN C_USUARIOS_ROL%NOTFOUND;
        END LOOP;
        CLOSE C_USUARIOS_ROL;
    END USUARIOS_POR_ROL_PRC;

    PROCEDURE USUARIOS_INACTIVOS_PRC IS
        CURSOR C_INACTIVOS IS
            SELECT u.CEDULA, u.NOMBRE
            FROM   FIDE_USUARIO_TB u
            JOIN   FIDE_ESTADO_TB e ON u.ID_ESTADO = e.ID_ESTADO
            WHERE  e.NOMBRE = 'Inactivo';
        V_CEDULA FIDE_USUARIO_TB.CEDULA%TYPE;
        V_NOMBRE FIDE_USUARIO_TB.NOMBRE%TYPE;
    BEGIN
        OPEN C_INACTIVOS;
        LOOP
            FETCH C_INACTIVOS INTO V_CEDULA, V_NOMBRE;
            EXIT WHEN C_INACTIVOS%NOTFOUND;
        END LOOP;
        CLOSE C_INACTIVOS;
    END USUARIOS_INACTIVOS_PRC;
END FIDE_USUARIO_PKG;
/

-- Paquete 4: FIDE_PROGRAMA_PKG (2 cursores)
CREATE OR REPLACE PACKAGE FIDE_PROGRAMA_PKG AS
    PROCEDURE PROGRAMAS_POR_CURSO_PRC(CP_ID_CURSO IN NUMBER);
    PROCEDURE PROGRAMAS_POR_ESTADO_PRC(CP_ID_ESTADO IN NUMBER);
END FIDE_PROGRAMA_PKG;
/
CREATE OR REPLACE PACKAGE BODY FIDE_PROGRAMA_PKG AS
    PROCEDURE PROGRAMAS_POR_CURSO_PRC(CP_ID_CURSO IN NUMBER) IS
        CURSOR C_PROG_CURSO(P_ID_CURSO NUMBER) IS
            SELECT ID_PROGRAMA, FECHA_CREACION FROM FIDE_PROGRAMA_TB WHERE ID_CURSO = P_ID_CURSO;
        V_ID FIDE_PROGRAMA_TB.ID_PROGRAMA%TYPE;
        V_FECHA FIDE_PROGRAMA_TB.FECHA_CREACION%TYPE;
    BEGIN
        OPEN C_PROG_CURSO(CP_ID_CURSO);
        LOOP
            FETCH C_PROG_CURSO INTO V_ID, V_FECHA;
            EXIT WHEN C_PROG_CURSO%NOTFOUND;
        END LOOP;
        CLOSE C_PROG_CURSO;
    END PROGRAMAS_POR_CURSO_PRC;

    PROCEDURE PROGRAMAS_POR_ESTADO_PRC(CP_ID_ESTADO IN NUMBER) IS
        CURSOR C_PROG_ESTADO(P_ID_ESTADO NUMBER) IS
            SELECT ID_PROGRAMA, ID_CURSO FROM FIDE_PROGRAMA_TB WHERE ID_ESTADO = P_ID_ESTADO;
        V_ID FIDE_PROGRAMA_TB.ID_PROGRAMA%TYPE;
        V_CURSO FIDE_PROGRAMA_TB.ID_CURSO%TYPE;
    BEGIN
        OPEN C_PROG_ESTADO(CP_ID_ESTADO);
        LOOP
            FETCH C_PROG_ESTADO INTO V_ID, V_CURSO;
            EXIT WHEN C_PROG_ESTADO%NOTFOUND;
        END LOOP;
        CLOSE C_PROG_ESTADO;
    END PROGRAMAS_POR_ESTADO_PRC;
END FIDE_PROGRAMA_PKG;
/

-- Paquete 5: FIDE_SOLICITUD_PKG (2 cursores)
CREATE OR REPLACE PACKAGE FIDE_SOLICITUD_PKG AS
    PROCEDURE SOL_MAYOR_PENDIENTES_PRC;
    PROCEDURE SOL_MENOR_PENDIENTES_PRC;
END FIDE_SOLICITUD_PKG;
/
CREATE OR REPLACE PACKAGE BODY FIDE_SOLICITUD_PKG AS
    PROCEDURE SOL_MAYOR_PENDIENTES_PRC IS
        CURSOR C_SOL_MAYOR IS
            SELECT s.ID_SOLICITUD, s.CEDULA
            FROM   FIDE_SOLICITUD_TB s
            JOIN   FIDE_ESTADO_TB e ON s.ID_ESTADO = e.ID_ESTADO
            WHERE  s.ID_TIPO_SOLICITUD = 2 AND e.NOMBRE = 'Pendiente';
        V_ID FIDE_SOLICITUD_TB.ID_SOLICITUD%TYPE;
        V_CEDULA FIDE_SOLICITUD_TB.CEDULA%TYPE;
    BEGIN
        OPEN C_SOL_MAYOR;
        LOOP
            FETCH C_SOL_MAYOR INTO V_ID, V_CEDULA;
            EXIT WHEN C_SOL_MAYOR%NOTFOUND;
        END LOOP;
        CLOSE C_SOL_MAYOR;
    END SOL_MAYOR_PENDIENTES_PRC;

    PROCEDURE SOL_MENOR_PENDIENTES_PRC IS
        CURSOR C_SOL_MENOR IS
            SELECT s.ID_SOLICITUD, s.CEDULA
            FROM   FIDE_SOLICITUD_TB s
            JOIN   FIDE_ESTADO_TB e ON s.ID_ESTADO = e.ID_ESTADO
            WHERE  s.ID_TIPO_SOLICITUD = 1 AND e.NOMBRE = 'Pendiente';
        V_ID FIDE_SOLICITUD_TB.ID_SOLICITUD%TYPE;
        V_CEDULA FIDE_SOLICITUD_TB.CEDULA%TYPE;
    BEGIN
        OPEN C_SOL_MENOR;
        LOOP
            FETCH C_SOL_MENOR INTO V_ID, V_CEDULA;
            EXIT WHEN C_SOL_MENOR%NOTFOUND;
        END LOOP;
        CLOSE C_SOL_MENOR;
    END SOL_MENOR_PENDIENTES_PRC;
END FIDE_SOLICITUD_PKG;
/

-- Paquete 6: FIDE_NOTIFICACION_PKG (2 cursores)
CREATE OR REPLACE PACKAGE FIDE_NOTIFICACION_PKG AS
    PROCEDURE NOTIF_POR_USUARIO_PRC(CP_CEDULA IN VARCHAR2);
    PROCEDURE NOTIF_POR_TIPO_PRC(CP_ID_TIPO IN NUMBER);
END FIDE_NOTIFICACION_PKG;
/
CREATE OR REPLACE PACKAGE BODY FIDE_NOTIFICACION_PKG AS
    PROCEDURE NOTIF_POR_USUARIO_PRC(CP_CEDULA IN VARCHAR2) IS
        CURSOR C_NOTIF_USUARIO(P_CEDULA VARCHAR2) IS
            SELECT n.ID_NOTIFICACION, n.ASUNTO
            FROM   FIDE_NOTIFICACION_USUARIO_TB nu
            JOIN   FIDE_NOTIFICACION_TB n ON nu.ID_NOTIFICACION = n.ID_NOTIFICACION
            WHERE  nu.CEDULA = P_CEDULA;
        V_ID FIDE_NOTIFICACION_TB.ID_NOTIFICACION%TYPE;
        V_ASUNTO FIDE_NOTIFICACION_TB.ASUNTO%TYPE;
    BEGIN
        OPEN C_NOTIF_USUARIO(CP_CEDULA);
        LOOP
            FETCH C_NOTIF_USUARIO INTO V_ID, V_ASUNTO;
            EXIT WHEN C_NOTIF_USUARIO%NOTFOUND;
        END LOOP;
        CLOSE C_NOTIF_USUARIO;
    END NOTIF_POR_USUARIO_PRC;

    PROCEDURE NOTIF_POR_TIPO_PRC(CP_ID_TIPO IN NUMBER) IS
        CURSOR C_NOTIF_TIPO(P_ID_TIPO NUMBER) IS
            SELECT ID_NOTIFICACION, ASUNTO FROM FIDE_NOTIFICACION_TB WHERE ID_TIPO_NOTIFICACION = P_ID_TIPO;
        V_ID FIDE_NOTIFICACION_TB.ID_NOTIFICACION%TYPE;
        V_ASUNTO FIDE_NOTIFICACION_TB.ASUNTO%TYPE;
    BEGIN
        OPEN C_NOTIF_TIPO(CP_ID_TIPO);
        LOOP
            FETCH C_NOTIF_TIPO INTO V_ID, V_ASUNTO;
            EXIT WHEN C_NOTIF_TIPO%NOTFOUND;
        END LOOP;
        CLOSE C_NOTIF_TIPO;
    END NOTIF_POR_TIPO_PRC;
END FIDE_NOTIFICACION_PKG;
/

-- Paquete 7: FIDE_CICLO_PKG (1 cursor)
CREATE OR REPLACE PACKAGE FIDE_CICLO_PKG AS
    PROCEDURE CICLOS_ACTIVOS_PRC;
END FIDE_CICLO_PKG;
/
CREATE OR REPLACE PACKAGE BODY FIDE_CICLO_PKG AS
    PROCEDURE CICLOS_ACTIVOS_PRC IS
        CURSOR C_CICLOS_ACTIVOS IS
            SELECT c.ID_CICLO, c.ANIO, c.CICLO
            FROM   FIDE_CICLO_ACADEMICO_TB c
            JOIN   FIDE_ESTADO_TB e ON c.ID_ESTADO = e.ID_ESTADO
            WHERE  e.NOMBRE = 'Activo';
        V_ID FIDE_CICLO_ACADEMICO_TB.ID_CICLO%TYPE;
        V_ANIO FIDE_CICLO_ACADEMICO_TB.ANIO%TYPE;
        V_CICLO FIDE_CICLO_ACADEMICO_TB.CICLO%TYPE;
    BEGIN
        OPEN C_CICLOS_ACTIVOS;
        LOOP
            FETCH C_CICLOS_ACTIVOS INTO V_ID, V_ANIO, V_CICLO;
            EXIT WHEN C_CICLOS_ACTIVOS%NOTFOUND;
        END LOOP;
        CLOSE C_CICLOS_ACTIVOS;
    END CICLOS_ACTIVOS_PRC;
END FIDE_CICLO_PKG;
/

-- Paquete 8: FIDE_VERSION_PKG (1 cursor)
CREATE OR REPLACE PACKAGE FIDE_VERSION_PKG AS
    PROCEDURE VERSIONES_POR_PROGRAMA_PRC(CP_ID_PROGRAMA IN NUMBER);
END FIDE_VERSION_PKG;
/
CREATE OR REPLACE PACKAGE BODY FIDE_VERSION_PKG AS
    PROCEDURE VERSIONES_POR_PROGRAMA_PRC(CP_ID_PROGRAMA IN NUMBER) IS
        CURSOR C_VERSIONES(P_ID_PROGRAMA NUMBER) IS
            SELECT ID_VERSION, NUMERO_VERSION FROM FIDE_VERSION_PROGRAMA_TB WHERE ID_PROGRAMA = P_ID_PROGRAMA;
        V_ID FIDE_VERSION_PROGRAMA_TB.ID_VERSION%TYPE;
        V_NUM FIDE_VERSION_PROGRAMA_TB.NUMERO_VERSION%TYPE;
    BEGIN
        OPEN C_VERSIONES(CP_ID_PROGRAMA);
        LOOP
            FETCH C_VERSIONES INTO V_ID, V_NUM;
            EXIT WHEN C_VERSIONES%NOTFOUND;
        END LOOP;
        CLOSE C_VERSIONES;
    END VERSIONES_POR_PROGRAMA_PRC;
END FIDE_VERSION_PKG;
/

-- Paquete 9: FIDE_REVISION_PKG (1 cursor)
CREATE OR REPLACE PACKAGE FIDE_REVISION_PKG AS
    PROCEDURE REVISIONES_POR_SOLICITUD_PRC(CP_ID_SOLICITUD IN NUMBER);
END FIDE_REVISION_PKG;
/
CREATE OR REPLACE PACKAGE BODY FIDE_REVISION_PKG AS
    PROCEDURE REVISIONES_POR_SOLICITUD_PRC(CP_ID_SOLICITUD IN NUMBER) IS
        CURSOR C_REVISIONES(P_ID_SOLICITUD NUMBER) IS
            SELECT CEDULA, COMENTARIO FROM FIDE_REVISION_SOLICITUD_TB WHERE ID_SOLICITUD = P_ID_SOLICITUD;
        V_CEDULA FIDE_REVISION_SOLICITUD_TB.CEDULA%TYPE;
        V_COMENTARIO FIDE_REVISION_SOLICITUD_TB.COMENTARIO%TYPE;
    BEGIN
        OPEN C_REVISIONES(CP_ID_SOLICITUD);
        LOOP
            FETCH C_REVISIONES INTO V_CEDULA, V_COMENTARIO;
            EXIT WHEN C_REVISIONES%NOTFOUND;
        END LOOP;
        CLOSE C_REVISIONES;
    END REVISIONES_POR_SOLICITUD_PRC;
END FIDE_REVISION_PKG;
/

-- Paquete 10: FIDE_BIBLIOGRAFIA_PKG (1 cursor)
CREATE OR REPLACE PACKAGE FIDE_BIBLIOGRAFIA_PKG AS
    PROCEDURE BIBLIOGRAFIA_POR_VERSION_PRC(CP_ID_VERSION IN NUMBER);
END FIDE_BIBLIOGRAFIA_PKG;
/
CREATE OR REPLACE PACKAGE BODY FIDE_BIBLIOGRAFIA_PKG AS
    PROCEDURE BIBLIOGRAFIA_POR_VERSION_PRC(CP_ID_VERSION IN NUMBER) IS
        CURSOR C_BIBLIOGRAFIA(P_ID_VERSION NUMBER) IS
            SELECT b.TITULO, b.AUTOR
            FROM   FIDE_VERSION_BIBLIOGRAFIA_TB vb
            JOIN   FIDE_BIBLIOGRAFIA_TB b ON vb.ID_BIBLIOGRAFIA = b.ID_BIBLIOGRAFIA
            WHERE  vb.ID_VERSION = P_ID_VERSION;
        V_TITULO FIDE_BIBLIOGRAFIA_TB.TITULO%TYPE;
        V_AUTOR FIDE_BIBLIOGRAFIA_TB.AUTOR%TYPE;
    BEGIN
        OPEN C_BIBLIOGRAFIA(CP_ID_VERSION);
        LOOP
            FETCH C_BIBLIOGRAFIA INTO V_TITULO, V_AUTOR;
            EXIT WHEN C_BIBLIOGRAFIA%NOTFOUND;
        END LOOP;
        CLOSE C_BIBLIOGRAFIA;
    END BIBLIOGRAFIA_POR_VERSION_PRC;
END FIDE_BIBLIOGRAFIA_PKG;
/


-- 5. TRIGGERS (5)


-- Trigger 1: fecha de registro automatica al insertar un usuario
CREATE OR REPLACE TRIGGER FIDE_USUARIO_FECHA_TRG
BEFORE INSERT ON FIDE_USUARIO_TB
FOR EACH ROW
BEGIN
    IF :NEW.FECHA_REGISTRO IS NULL THEN
        :NEW.FECHA_REGISTRO := SYSDATE;
    END IF;
END;
/

-- Trigger 2: fecha de envio automatica al insertar una notificacion
CREATE OR REPLACE TRIGGER FIDE_NOTIFICACION_FECHA_TRG
BEFORE INSERT ON FIDE_NOTIFICACION_TB
FOR EACH ROW
BEGIN
    IF :NEW.FECHA_ENVIO IS NULL THEN
        :NEW.FECHA_ENVIO := SYSDATE;
    END IF;
END;
/

-- Trigger 3: registrar fecha de solicitud automatica si no viene informada
CREATE OR REPLACE TRIGGER FIDE_SOLICITUD_FECHA_TRG
BEFORE INSERT ON FIDE_SOLICITUD_TB
FOR EACH ROW
BEGIN
    IF :NEW.FECHA_SOLICITUD IS NULL THEN
        :NEW.FECHA_SOLICITUD := SYSDATE;
    END IF;
END;
/

-- Trigger 4: al actualizar el estado de una solicitud a Aprobado/Rechazado,
-- completar automaticamente la fecha de respuesta
CREATE OR REPLACE TRIGGER FIDE_SOLICITUD_RESPUESTA_TRG
BEFORE UPDATE OF ID_ESTADO ON FIDE_SOLICITUD_TB
FOR EACH ROW
DECLARE
    V_NOMBRE_ESTADO VARCHAR2(50);
BEGIN
    SELECT NOMBRE INTO V_NOMBRE_ESTADO FROM FIDE_ESTADO_TB WHERE ID_ESTADO = :NEW.ID_ESTADO;
    IF V_NOMBRE_ESTADO IN ('Aprobado', 'Rechazado') AND :NEW.FECHA_RESPUESTA IS NULL THEN
        :NEW.FECHA_RESPUESTA := SYSDATE;
    END IF;
END;
/

-- Trigger 5: al registrar una revision de solicitud, sincronizar el estado
-- de la solicitud correspondiente
CREATE OR REPLACE TRIGGER FIDE_REVISION_SINCRONIZA_TRG
AFTER INSERT ON FIDE_REVISION_SOLICITUD_TB
FOR EACH ROW
BEGIN
    UPDATE FIDE_SOLICITUD_TB
    SET ID_ESTADO = :NEW.ID_ESTADO,
        FECHA_RESPUESTA = NVL(FECHA_RESPUESTA, SYSDATE)
    WHERE ID_SOLICITUD = :NEW.ID_SOLICITUD;
END;
/
